docs/contribute/principles-of-a-good-tutorial.md, sidebars.js
I've summarized [this comment](https://github.com/ton-society/ton-footsteps/issues/7#issuecomment-1187581181), originally written by @talkol
=> Add Principles of a Good Tutorial

docs/participate/wallets/contracts.md
=> Cover "Wallet Contracts" article

docs/participate/wallets/apps.md
=> small text fix

docs/develop/howto/fees_low_level.md
Refactored text about GAS price into table.
=> gas_price_table

docs/participate/wallets/apps.md
Added up-to-date information about Tohub (switched to testnet) and some little fixes in the wallet article.
=> Wallets article update

docs/develop/smart-contracts/guidelines.md
=> add video from TON developers

docs/develop/smart-contracts/README.md
=> Fix JS naming

docusaurus.config.js
=> D danev/change base url

docusaurus.config.js
=> fix base url

docusaurus.config.js
=> fix ton docs url

docusaurus.config.js
=> fix basePath, fix url

docs/develop/smart-contracts/guidelines/internal-messages.md
Add data on long message comments
It is important for smart-contract, explorers and wallet developers to be able uniformly display long text messages
=> Add info on long message comments

docs/learn/tvm-instructions/tvm_exit_codes.md
```
"Asm.fif" include
<{ 0 PUSHINT SETGASLIMIT 0 PUSHINT }>s runvmcode
."Exit code: " (dump) type drop cr
```
=> Fix tvm exit codes

docs/develop/dapps/tutorials/jetton-minter.md
=> added info box

docs/develop/smart-contracts/tutorials/multisig.md
1. Added some additional information for new-comers.
2. Little fixes corespondly author's comments.
=> multisig_tutorial_update

docs/develop/dapps/defi/tokens.md
=> Add NFT Minter on Golang

.github/ISSUE_TEMPLATE/suggest_tutorial.yaml
Just a chore
Fix issue template for `.github/ISSUE_TEMPLATE/suggest_tutorial.yaml. There is warning about(see img)
[More about warning](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#bodyi-options-must-be-unique)
=> chore: remove duplicated option

docs/develop/func/cookbook.md
covered these examples for the footstep:
https://github.com/ton-society/ton-footsteps/issues/10#issuecomment-1346586701
=> added examples in cookbook

docs/develop/func/cookbook.md
This will highlight func syntax in code
=> docs: specifying func for code blocks

docs/develop/func/cookbook.md
I also fixed links from previous examples. They were absolute (like https://ton.org/docs/...) and I replaced them with just /docs/...
=> 10 new examples in cookbook

docs/develop/smart-contracts/testing/toncli.md
Added explanations to the types of output data and a COMPLETE guide to writing texts for a smart contract.
=> Updated an article "toncli" in testing smart contracts

docs/develop/smart-contracts/sdk/toncli.md
Added an environment installation guide with explanations for different systems and an example of creating a project.
=> Updated an article "toncli" in sdk

docs/participate/ton-storage/storage-daemon.md
There are recent minor improvements in storage-daemon and storage-daemon-cli that are not covered in docs.
=> Document recent updates of storage-daemon

docs/develop/fift-deep-dive.md, sidebars.js
Most people don't see difference between Fift and TVM assembly.
Confusion is increased by the fact that there is no good documentation on Fift, though there's one on TVM assembly opcodes.
https://github.com/ton-society/ton-footsteps/issues/110
=> Added an article "Fift deep dive"

docs/develop/func/cookbook.md
We need to provide examples in the most understandable format. It would be great if each example had a description (what problem? how to solve? why?), useful links and comments. This will help developers get into FunC development faster.
I've already changed some of the examples, and added comments to all the others. Please pay attention to `TODO` in changes: this is the place where you need to add or change something.
=> docs: added edits and comments to cookbook

docs/develop/smart-contracts/tutorials/multisig.md
Changed broken link to the correct one
=> Broken mainnet global-config.json link

docs/participate/ton-storage/storage-provider.md
Update smart contract source code link to point to master branch
This change is important because it updates the link to point to the correct location of the smart contract source code, which is now on the master branch.
None
=> Update smart contract source code link to point to master branch

docs/learn/introduction.mdx, src/components/button.tsx, src/css/custom.css
Add new buttons;
Primary and secondary
can be used in mdx/tsx/jsx
=> add new buttons

.github/workflows/build-demo.yml, .github/workflows/build-prod.yml, .github/workflows/build-staging.yml
=> add deploy ton-docs staging

docs/develop/func/cookbook.md, docs/develop/func/stdlib.mdx
=> Fixes & improvements (mainly TODO)

docs/develop/dapps/ton-connect/integration.md
Changed style of some article parts.
https://github.com/ton-community/ton-docs/pull/135#issuecomment-1400146391
=> Improvements in integration manual for TON Connect

docs/develop/func/stdlib.mdx
=> Send modes table

sidebars.js
=> side-bar-fix

docs/develop/tact/tact-overview.mdx
=> tact-overview-gas-control-cut

docs/develop/tact/introduce/hello-world-guide.md
Just fixed some English mistakes, nothing major
=> fixed some typos and grammar mistakes

docs/develop/smart-contracts/compile/README.md, docs/develop/smart-contracts/sdk/javascript.md, docs/develop/smart-contracts/sdk/tonstarter.md
=> Blueprint references import

docs/develop/howto/faq.md
Added digits info and testnet link in the FAQ.
=> Faq update

docs/develop/dapps/apis/toncenter.md
Fix formatting, easier to read points
=> Fix formatting in TON Center API

docs/develop/fift/overview.mdx
=> fixed a couple of typos

docs/develop/func/cookbook.md
=> Add 3 examples to cookbook

docs/develop/func/functions.md
=> Update for `inline` example

docs/develop/fift/overview.mdx
Added link to English version of Fift tutorials.
=> fift_overview_update

docs/develop/smart-contracts/fees.md
Script for calculating yearly storage probably has typo
=> Fix cell count in cost estimation for storage

docs/develop/data-formats/crc32.md, docs/develop/data-formats/tlb-ide.md, docs/learn/overviews/addresses.md
=> fix_weeakly_update

README.md
=> nodejs_version_clarified

docs/develop/data-formats/tlb-ide.md
=> add tongo to TL-B parsers

docs/develop/dapps/README.md
=> Update tongo urls

docs/develop/smart-contracts/tutorials/wallet.md, sidebars.js
The tutorial covers the entire topic of wallet smart contracts, internal and external messages, and some details about the structure of the TON blockchain.
=> How to work with wallet smart contracts

docs/develop/getting-started.mdx, docs/develop/smart-contracts/README.mdx
=> wallet-tutorial-links-added

docs/participate/nodes/archive-node.md, sidebars.js
=> Run an Archive Node guide added

docs/participate/nodes/archive-node.md
- Cut excess step
- Fixed minimal requirements
=> run-arch-node-guide-fix

package-lock.json, package.json
=> revert-confgs

docs/develop/dapps/ton-connect/tg-bot-integration.md, docs/develop/smart-contracts/tutorials/wallet.md, docs/participate/network-maintenance/staking-incentives.md, docs/participate/run-nodes/archive-node.md, docs/participate/wallets/apps.md, docs/participate/wallets/contracts.md
fixes for links and references
=> Update fix 1

docs/learn/services/sites-www-proxy.md
=> Mention JUSTON's dApp browser for open .ton Sites

docs/participate/web3/sites-and-proxy.md
This is very cosmetic changes just to have a more consistent formatting style
1. Use syntax highlighting
2. Add required indents for better formatting
3. Removed inconsistently used `:`
<details>
<summary>Please see one example of the current and updated text</summary>
</details>
It is suitable to have a consistent format documentation with aligned text and paragraphs. If we use `:` somewhere for some reason, we should follow such approach in all similar cases, if not - let's remove it.
=> Cosmetic changes to follow better formatting

docusaurus.config.js
=> fix-top-bar-menu

docs/develop/companies/outsource.md, docusaurus.config.js
=> outsource_update

docs/develop/smart-contracts/guidelines/message-delivery-guarantees.mdx
There was a wrong example, so I decided to update this article.
=> update message-delivery-guarantees article

docs/develop/smart-contracts/tutorials/wallet.md
Correcting the wrong spelling in docs.
=> correct spelling

docusaurus.config.js
=> Fix-redirect-error

docusaurus.config.js, sidebars.js
=> weekly_update_20-2

docs/develop/dapps/README.md, docs/develop/dapps/apis/adnl.md
Added link to open source Rust SDK for The Open Network made by ston.fi 
Open source solution for the TON community
=> Add link for Rust SDK

docs/develop/smart-contracts/libraries.md
=> Add funcbox

docs/develop/smart-contracts/guidelines/random-number-generation.md
There were some mistakes. I updated the article.
=> update Random Number Generation article

docs/participate/nodes/node-types.md, docs/participate/run-nodes/liteserver.mdx, sidebars.js
[Footstep 249](https://github.com/ton-society/ton-footsteps/issues/249)
=> liteserver launching tutorial

docs/develop/smart-contracts/guidelines/get-methods.md
Closes https://github.com/ton-society/ton-footsteps/issues/250
=> Documentation for Get Methods (Getters) in TON Blockchain

docs/develop/howto/subresolvers.md, sidebars.js
Currently, documentation does not feature how to build subdomain resolvers for TON DNS, and for existing resolvers (auto-dns and manual-dns) it only links to code, hindering technology adoption.
https://github.com/ton-society/ton-footsteps/issues/251
=> TON DNS resolvers article

docs/develop/get-started-with-ton.mdx
One line of text is repeated two times, probably by mistake. I removed one of the duplicating lines (the one that looked to me like it was in the wrong place). Also I inserted a missing space.
=> Removed a duplicating line

docs/develop/companies/auditors.mdx, docs/develop/dapps/apis/README.md, docs/develop/dapps/apis/adnl.md, docs/develop/dapps/apis/sdk.mdx, docs/develop/dapps/apis/toncenter.md, docs/develop/howto/fees-low-level.md, docs/develop/smart-contracts/README.mdx, docs/develop/smart-contracts/sdk/javascript.md, docs/learn/overviews/addresses.md
* TON SDKs list page added
* Added links to SDKs 
* Blueprint and Sandbox links updated (migration to the [ton-org](https://github.com/ton-org) organization).
* Minor updates in API page description according to the new SDKs page.
=> Weekly update 27

docs/develop/data-formats/tl-b-language.mdx
=> Update tlb docs

docs/develop/data-formats/tl-b-language.mdx
=> Fix ThemedImage

docs/develop/data-formats/tl-b-language.mdx
=> Fix import ThemedImage in tlb

docs/develop/data-formats/tl-b-language.mdx
=> Small fixes in TLB

docs/develop/func/builtins.md
Added func built-in divmod function.
=> Added divmod in builtins.md

docs/develop/data-formats/cell-boc.mdx, docs/develop/data-formats/exotic-cells.md, docs/develop/data-formats/proofs.mdx, sidebars.js
These articles are important for trustless communication with the Blockchain.
=> Exotic Cells article and Liteserver Merkle proofs verifying examples

docs/develop/dapps/tutorials/overview.mdx, docs/develop/dapps/tutorials/simple-zk-on-ton.md, sidebars.js
With the latest [TVM upgrade](https://docs.ton.org/learn/tvm-instructions/tvm-upgrade-2023-07#bls12-381), Zero-Knowledge proofs can be verified on TON blockchain with a reasonable fee. This could open doors to the devs and projects who want to take advantage of this technology in their products. 
I believe this tutorial could save plenty of time and effort for existing/new developers in TON ecosystem to build their first ZK project on TON.
#302 
[ZKSnark Footstep](https://github.com/ton-society/ton-footsteps/issues/22)
[TVM Upgrade Disscusion](https://github.com/ton-blockchain/TEPs/pull/88)
PS: This is my first contribution to this repo so I might have made some rookie mistakes:)
=> Simple Zero-Knowledge project on TON

docs/develop/dapps/tutorials/simple-zk-on-ton.md, docusaurus.config.js
- Add simple zk to the dropdown in the header
- fix some external links
#304
=> Add Simple ZK to dropdown

docs/develop/data-formats/tl-b-language.mdx
We recently found out that feature with @tvorogme
=> add special type of hex tags for tlb

docs/develop/dapps/ton-connect/message-builders.mdx, docs/develop/dapps/ton-connect/transactions.md
improved description and fixed minor issues
=> messages_page_updated

docs/develop/dapps/ton-connect/message-builders.mdx
=> added_switcher_update_1

docs/develop/dapps/ton-connect/message-builders.mdx
Tabs(@react-ui/@ui/@ton-connect/sdk added) for all JS examples
=> added_tabs_react_and_js_examples

docs/develop/get-started-with-ton.mdx
=> Fix typo in get-started-with-ton.mdx

docs/develop/data-formats/crc32.md
To better understand, adding TS example to get the code.
NONE
=> Update crc32.md content, adding Typescript example

docs/develop/dapps/ton-connect/developers.md, docs/develop/dapps/ton-connect/integration.md, docs/develop/dapps/ton-connect/manifest.md, docs/develop/dapps/ton-connect/message-builders.mdx, docs/develop/dapps/ton-connect/overview.mdx, docs/develop/dapps/ton-connect/protocol/requests-responses.md, docs/develop/dapps/ton-connect/protocol/wallet-guidelines.md, docs/develop/dapps/ton-connect/react.mdx, docs/develop/dapps/ton-connect/sign.mdx, docs/develop/dapps/ton-connect/tg-bot-integration.md, docs/develop/dapps/ton-connect/transactions.md, docs/develop/dapps/tutorials/simple-zk-on-ton.md, docs/develop/func/overview.md, docs/develop/overview.mdx, docs/develop/smart-contracts/examples.md, docs/participate/wallets/contracts.md, sidebars.js, static/img/docs/ton-connect/ton_proof_scheme-dark.svg, static/img/docs/ton-connect/ton_proof_scheme.svg
- Sign and Verification page improvements.
- dApps -> DApps, dApp -> DApp replaced.
- Examples for TON Connect messages minor fixes and updates.
=> Weekly update 33

docs/develop/func/overview.md, docs/develop/smart-contracts/examples.md, docs/develop/smart-contracts/testing/overview.mdx
Improvement for the description of testing contracts.
=> Test docs improvements

docs/develop/dapps/ton-connect/developers.md
Related to [ton-society/ton-footsteps#276](https://github.com/ton-society/ton-footsteps/issues/276)
=> Add C# Library and Unity Asset for TonConnect 2.0 to Ton.Docs

docs/develop/dapps/tutorials/simple-zk-on-ton.md
The suggested version has been proofread and edited
=> Edited simple-zk-on-ton.md

docs/develop/dapps/tutorials/accept-payments-in-a-telegram-bot-js.md
grammY is the correct way to spell this library so it should be done that way
None
=> fix: casing in accept-payments-in-a-telegram-bot-js.md

docs/develop/dapps/apis/toncenter.md
Add a new node provider as Chainbase
We want to contribute to the TON system and provide a free TON RPC for developers.
=> Update toncenter.md for node provider

docs/develop/companies/auditors.mdx, docs/develop/companies/outsource.mdx, docs/develop/dapps/apis/README.md, docs/develop/dapps/apis/adnl.md, docs/develop/dapps/apis/sdk.mdx, docs/develop/dapps/apis/toncenter.md, docs/develop/dapps/asset-processing/README.md, docs/develop/get-started-with-ton.mdx, docs/participate/wallets/apps.mdx
Updated information about TON Blockchain wallets
Some information about wallets was outdated, and needed to be updated.
#360
=> Wallets documentation update, as well as fix many typos

docs/develop/dapps/asset-processing/jettons.md
=> Fix small typo

package-lock.json
Updating dependencies is an essential aspect of software development, and it's crucial for maintaining a secure, stable, and efficient   
#366
=> PR Request For Updating Dependency.

docs/participate/ton-storage/storage-faq.md
=> Make storage-faq.md a little more readable

docs/develop/dapps/ton-connect/tg-bot-integration.md
This project is required to demonstrate the integration between TON Connect and Telegram Bot and showcase the capabilities of TON Connect. The existing showcase on GitHub needs improvement to ensure that the example bot is enabled and supports authorization with https://github.com/wallet.
[Update TON Connect Telegram Bot Showcase #315](https://github.com/ton-society/grants-and-bounties/issues/315)
=> fix: updated tg bot TonConnect integration tutorial -- @wallet supported

docs/develop/dapps/cookbook.md
=> Add 2 basic examples to TON Cookbook

docs/develop/dapps/telegram-apps/step-by-step-guide.mdx, docs/develop/dapps/telegram-apps/tips-and-tricks.mdx
Little update for the TMA Tips and Tricks page.
=> tma_tips_and_tricks_update

docs/develop/smart-contracts/environment/ide-plugins.md
=> Slight grammar adjustments to IDE Plugins.

docs/develop/get-started-with-ton.mdx
Minor develop/get-started-with-ton.mdx refactoring
To better understanding
=> Minor develop/get-started-with-ton.mdx refactoring

docs/develop/smart-contracts/README.mdx
=> Slight grammar adjustments to Smart Contracts Intro

docs/learn/glossary.md
=> Fix grammar mistake

docs/develop/get-started-with-ton.mdx, docs/participate/wallets/apps.mdx
=> Added a brief introductory sentence before the list to provide context

docs/learn/glossary.md
=> Correcting visual error in text

docs/develop/companies/outsource.mdx
Our website:
* https://coinvent.dev
=> Add Coinvent to the list of outsource development teams

docs/develop/dapps/telegram-apps/step-by-step-guide.mdx, docusaurus.config.js, sidebars.js
=> TMA-section-update

docs/develop/howto/fees-low-level.md
omit redundant ' , please check diff it is obvious
=> tiny spell correction

docs/develop/dapps/apis/sdk.mdx, docs/develop/dapps/ton-connect/developers.md
Add TonSDK adnl reference.
Add TonSDK adnl reference.
=> Add TonSDK adnl reference.

docs/develop/dapps/apis/sdk.mdx
Added [tonkite/adnl](https://github.com/tonkite/adnl)
Provides native ADNL for nodeJS and WebSocket implementation (for browsers)
=> Added tonkite/adnl

docs/learn/archive/tvm-instructions.mdx, sidebars.js
Added old version of TVM Instructions page to Archive, although, I am not sure if we should add any kind of a warning message there
=> Add old version of TVM Instructions to Archive

docs/develop/dapps/asset-processing/README.md
=> fix broken link.md

docs/develop/dapps/cookbook.md
=> Add pytoniq examples

docs/develop/smart-contracts/tutorials/wallet.md
https://ton.org/ton.pdf is retured 404 ,I replace it by https://doc.ton.org/ton.pdf; Now it works
=> fix broken link

docs/participate/explorers.mdx
=> exploerers-address-alias-info

docs/develop/dapps/ton-connect/developers.md
=> Add link to TON Connect Go SDK

docs/develop/func/overview.md
=> func-contest-descr-update

docs/develop/dapps/ton-connect/developers.md, docs/develop/func/stdlib.mdx, docs/develop/howto/network-configs.md, docs/develop/smart-contracts/messages.md, docs/develop/smart-contracts/testing/overview.mdx, docs/participate/network-maintenance/staking-incentives.md
=> Weekly update 24 3

.editorconfig, .eslintignore, .eslintrc.js, .github/workflows/lint.yml, package-lock.json, package.json, src/theme/prism-include-languages.js
=> Add eslint linting

docs/develop/dapps/apis/README.md, docs/develop/dapps/apis/toncenter.md, docs/develop/dapps/asset-processing/README.md, docs/develop/dapps/asset-processing/jettons.md, docs/develop/dapps/cookbook.md, docs/develop/smart-contracts/guidelines/accept.md, docs/develop/smart-contracts/guidelines/message-delivery-guarantees.mdx, docs/develop/smart-contracts/guidelines/processing.md, docs/participate/run-nodes/full-node.mdx, sidebars.js
- [Jetton Processing Guidelines](https://docs.ton.org/develop/dapps/asset-processing/jettons) updated
- Minor fixes and updates
=> Weekly update 24-5

docs/develop/dapps/ton-connect/sign.mdx
=> Add rust ton_proof demo

docs/develop/companies/outsource.mdx
Added softstack.io
Added softstack.io (formerly known as Chainsulting), who is working with ecosystem projects on on development and smart contract auditing.
=> Update outsource.mdx adding softstack

docs/participate/wallets/apps.mdx
=> Updated apps.mdx Changed typo

docs/develop/dapps/cookbook.md
=> Fix python script for jetton transfer

docs/learn/tvm-instructions/instructions.csv
New TVM Instructions were added to the main source of data (json files), but I forgot to update the csv table
=> Add new TVM instructions to the instructions.csv

docs/develop/dapps/ton-connect/sign.mdx
Reworded documentation for sign in verification on backend, to make it clearer for people not familiar with TON. Though this is according to my understanding of the process based on the same page, and I may misunderstand it.
Just improved the language here and there in a single sign.mdx file. I didn't change the sign in verification process image though.
=> Reworded sign.mdx

docs/develop/companies/auditors.mdx
Chainsulting just rebranded to softstack, check the new website https://softstack.io for reference.
Chainsulting just rebranded to softstack and needed to reflect the change, by updating the documentation.
=> Update auditors.mdx edited Chainsulting entry

docs/develop/dapps/README.mdx, docs/develop/dapps/apis/adnl.md, docs/develop/dapps/apis/sdk.mdx, docs/develop/dapps/apis/toncenter.md, docs/develop/dapps/cookbook.md, docs/develop/dapps/defi/nft.md, docs/develop/dapps/defi/subscriptions.md, docs/develop/dapps/defi/tokens.mdx, docs/develop/dapps/telegram-apps/README.mdx, docs/develop/smart-contracts/messages.md, docusaurus.config.js, sidebars.js, static/img/interaction-schemes/ecosystem.svg, static/img/interaction-schemes/jettons.svg, static/img/interaction-schemes/nft.svg, static/img/interaction-schemes/wallets.svg
This PR structures information for readers' convenience, providing links to other articles and noting which standard is responsible for each operation.
Schemes are prototypes only yet and may be visually unattractive.
https://github.com/ton-society/grants-and-bounties/issues/467
=> Updates in SDK and cookbook pages

docs/develop/dapps/apis/adnl.md, docs/develop/dapps/apis/toncenter.md, docs/participate/run-nodes/full-node.mdx
=> Weekly update 24 13

i18n/zh-Hans/docusaurus-plugin-content-pages/index.tsx
=> fix main page mobile view problem

docs/develop/dapps/asset-processing/README.md, docs/participate/wallets/contracts.md
=> High-load wallet v3 description

docs/develop/dapps/asset-processing/README.md, docs/develop/dapps/asset-processing/jettons.md, docs/develop/howto/blockchain-configs.md, docs/develop/smart-contracts/core-contracts/precompiled.md, docs/develop/smart-contracts/governance.md, sidebars.js
=> Weekly update 24 15

docs/develop/blockchain/shards.mdx
Touched up wording and punctuation.
The material part of the document is unchanged, just minor corrections.
=> Wording corrections in Shards

docs/develop/companies/outsource.mdx
Edit a few details at the softstack entry 
We had to edit the telegram username for direct contact to our sales and edit the company description, to better reflect our branding.
=> Update outsource.mdx edit details at softstack

docs/develop/dapps/ton-connect/overview.mdx
=> improving the ton сonnect section

docs/participate/nodes/node-types.md, docs/participate/run-nodes/archive-node.md, docs/participate/run-nodes/full-node.mdx
=> Add port forwarding section (run node over the NAT)

docs/develop/dapps/ton-connect/message-builders.mdx
=> Add TON Connect Go SDK Examples

docs/develop/dapps/tutorials/simple-zk-on-ton.md
There is a duplicate of pretty same string in docs.
=> Fix typo. simple-zk-on-ton.md

docs/develop/smart-contracts/messages.md
[528](https://github.com/ton-community/ton-docs/issues/528)
Changes:
=> Fix Not complete information on messages

docs/develop/dapps/ton-connect/developers.md
Idk why, but it was outdated, but for now its not outdated sdk
=> Update developers.md | Add Unity Tonconnect sdk links

docs/develop/func/stdlib.mdx
Fix link
https://github.com/ton-community/ton-docs/issues/571#issue-2280759946
=> HotFix: fix link

docs/develop/dapps/ton-connect/tg-bot-integration.mdx
This pull request corrects a typo in the documentation of the TonConnect demo telegram bot project. The typo is in the variable name `WALLETS_LIST_CAHCE_TTL_MS`, which should be `WALLETS_LIST_CACHE_TTL_MS`. This correction is important for clarity and to ensure that the documentation accurately reflects the codebase.
This pull request is related to a previous contribution (https://github.com/ton-connect/demo-telegram-bot/pull/2) where the typo in the code was fixed. This current pull request aims to update the documentation accordingly to maintain consistency between the code and the documentation.
=> Fix typo in documentation related to TonConnect demo telegram bot project

docs/develop/oracles/about_blockchain_oracles.md
[#537](https://github.com/ton-community/ton-docs/issues/537)
=> Updated the article about oracles

docs/develop/func/cookbook.md, docs/develop/howto/faq.md
[#593](https://github.com/ton-community/ton-docs/issues/593)
=> Added information about upgradable smart-contracts and an example

docs/develop/overview.mdx, i18n/mandarin/docusaurus-plugin-content-docs/current/develop/overview.mdx
Change the order of "_TON Hello World_" and "_Get Started with TON_" to match the button order below for better intuitiveness
Better intuitiveness
[#578](https://github.com/ton-community/ton-docs/issues/578)
=> Polish the development overview document

docs/learn/overviews/addresses.md
=> Add dton.io address convertion

docs/develop/howto/fees-low-level.md, docs/develop/smart-contracts/fee-calculation.md, docs/develop/smart-contracts/fees.md, sidebars.js
Add page about fees calculation
(a lot of text, so without image)
Small refactoring of low-level-fees-overview and Transaction-Fees pages
to 
and
to
Pls, use squash :)
[584](https://github.com/ton-community/ton-docs/issues/584)
=> Dynamic fee calculation

docs/develop/dapps/apis/toncenter.md, docs/participate/explorers.mdx
[#599](https://github.com/ton-community/ton-docs/issues/599)
=> Adding information about explorers, monitoring

docs/develop/howto/faq.md
[#606](https://github.com/ton-community/ton-docs/issues/606)
=> Added question about front-running

docs/develop/companies/outsource.mdx
=> Add pixelplex to outsource

docs/develop/smart-contracts/messages.md
=> fixed a typo

docs/develop/dapps/ton-connect/message-builders.mdx
=> Wrong opcode

docs/develop/companies/auditors.mdx
=> Trail Of Bits Add to the list of auditors

docs/develop/dapps/README.mdx, docs/develop/dapps/defi/tokens.mdx, docs/develop/overview.mdx, docs/develop/smart-contracts/README.mdx, docs/develop/smart-contracts/security/README.mdx, docs/learn/academy/academy-overview.md, docs/learn/introduction.mdx, docs/learn/tvm-instructions/tvm-overview.mdx
=> Adding Stepik courses in all the right places

docs/develop/smart-contracts/tutorials/wallet.md
- Changed plural to singular per context
- Added an apostrophe to the "it is" contraction -> "it's". It was written at "its" prior to this proposed change
=> fixed two typos

i18n/mandarin/docusaurus-plugin-content-docs/current/participate/run-nodes/full-node.mdx
=> Fix image links

docs/develop/dapps/tutorials/send-transactions-from-highload.md
Guide about sending transactions with highload wallet v3
There wasn't docs for it
=> [TON-350] add(article): Highload wallet v3 transactions

docs/develop/companies/auditors.mdx
=> sap-list-update

docs/learn/overviews/addresses.md
=> Description of address status and possible problems with addresses

docs/develop/dapps/ton-connect/protocol/bridge.md
=> Update bridge.md typo

docs/develop/dapps/asset-processing/jettons.md, docs/develop/dapps/tutorials/jetton-minter.md
=> Add jetton minter sub article

docs/develop/dapps/apis/sdk.mdx
Added a link and a brief description of the PHP SDK to the list
=> Update SDK's list

docs/develop/dapps/ton-connect/sign.mdx
=> add backend example for ton proof

docs/develop/dapps/README.mdx, docs/develop/dapps/defi/tokens.mdx, docs/develop/func/overview.mdx, docs/develop/overview.mdx, docs/develop/smart-contracts/README.mdx, docs/develop/smart-contracts/guidelines.mdx, docs/develop/smart-contracts/security/README.mdx, docs/learn/introduction.mdx, docs/learn/tvm-instructions/tvm-overview.mdx, i18n/zh-CN/docusaurus-plugin-content-docs/current/develop/dapps/README.mdx, i18n/zh-CN/docusaurus-plugin-content-docs/current/develop/dapps/defi/tokens.mdx, i18n/zh-CN/docusaurus-plugin-content-docs/current/develop/func/overview.mdx, i18n/zh-CN/docusaurus-plugin-content-docs/current/develop/overview.mdx, i18n/zh-CN/docusaurus-plugin-content-docs/current/develop/smart-contracts/README.mdx, i18n/zh-CN/docusaurus-plugin-content-docs/current/develop/smart-contracts/guidelines.mdx, i18n/zh-CN/docusaurus-plugin-content-docs/current/develop/smart-contracts/security/README.mdx, i18n/zh-CN/docusaurus-plugin-content-docs/current/learn/introduction.mdx
Added RU and CHN links as well as replaced EN -> CHN in CHN pages
We have translated Stepik courses that have not received attention from people speaking the relevant languages.
=> Stepik corrections

docs/participate/run-nodes/full-node.mdx
Added the AWS instance type fit for validators.
=> Add AWS instance description

docs/develop/dapps/tutorials/how-to-run-ton-site.md, docs/participate/web3/app-sites.mdx, docs/participate/web3/how-to-open-any-ton-site.md, sidebars.js
* TON Sites for Apps added
* Link for C++ implementation of proxy added
=> tons_sites_for_apps_page_added

docs/develop/func/functions.md
I've clarified the explanation of the inline specifier and added a new example. Previously it was difficult for newcomers without a background in C-like languages to understand
=> Update inline specifier explanation

docs/develop/dapps/apis/sdk.mdx, docs/develop/dapps/ton-connect/integration.md, docs/develop/dapps/ton-connect/tg-bot-tonapi-nft.md, docs/develop/dapps/tutorials/send-transactions-from-highload.md
=> Remove tonsdk

docs/participate/run-nodes/full-node.mdx
=> Test nodes

docs/participate/run-nodes/full-node.mdx, docs/participate/run-nodes/nodes-troubleshooting.md
=> Add information about node setup timings

docs/develop/smart-contracts/fees.md
=> chrore: add info about gasless transactions

docs/develop/archive/tg-bot-integration-py.md, docs/develop/archive/tg-bot-integration.mdx, sidebars.js
=> feat: ton connect tg bot integration archived

docs/participate/run-nodes/full-node.mdx, docs/participate/run-nodes/nodes-troubleshooting.md
=> Add error of wrong user usage for nodes

docs/develop/func/cookbook.md
=> Update cookbook.md date->data

docs/develop/dapps/asset-processing/README.md, docs/develop/dapps/cookbook.mdx
=> Add transaction and messages hashes examples

i18n/ja/docusaurus-plugin-content-docs/current.json
add Japanese content document translation
=> add Japanese content document translation

docs/develop/dapps/cookbook.mdx, package-lock.json
=> Added an example of how to send a transaction with Wallet V5

docs/participate/wallets/contracts.md
=> Added actual link to wallet v5

docs/participate/wallets/apps.mdx
=> feat: upd mytonwallet switch testnet info

i18n/ko/code.json
supplement i18n Korean translation
=> supplement i18n Korean translation

i18n/ja/code.json
=> add i18n ja translation

docs/develop/dapps/apis/sdk.mdx
=> Added tonutils SDK to the Python SDKs section

i18n/ja/docusaurus-plugin-content-docs/current.json, i18n/ko/docusaurus-plugin-content-docs/current.json
complete Japanese and Korean translations
=> Added translation

docs/develop/dapps/asset-processing/README.md, docs/develop/dapps/asset-processing/jettons.md, docs/develop/dapps/asset-processing/mass-mint-tools.mdx, docs/develop/dapps/asset-processing/mass_mint_tools.mdx, docs/develop/dapps/asset-processing/mintless-jettons.mdx, docs/participate/network-maintenance/nominator-pool.mdx, docs/participate/network-maintenance/staking-incentives.md, docs/participate/run-nodes/archive-node.md, docs/participate/run-nodes/become-validator.md, docs/participate/run-nodes/full-node.mdx, sidebars.js
Updated node documentation, added clarification on Validator slashing policy
New updates before new highload project launching
- Slashing Policy
- Validators Maintain Guidelines
- Support Contacts
- Mass Minting Tools
- Wallet Collector deployment for different shard
- Mintless Jettons Processing
=> nodes_documentation_fine_update

docs/develop/dapps/asset-processing/jettons.md
=> feat: clarified jetton errors information

docs/develop/dapps/ton-connect/message-builders.mdx
=> feat: add examples with assets sdk for message builders

src/theme/prism/prism-func.js, src/theme/prism/prism-tact.js
* Updates [⚡ Tact](https://tact-lang.org) language definition from 1.2.0 to 1.5.0
* Makes a complete overhaul of [💎 FunC](https://docs.ton.org/develop/func/overview) language definition ([with tests and all](https://github.com/novusnota/prism-ton)), updating it from 0.2.0 to the most modern 0.4.4 version
P.S.: Upstream source, with credits to original authors and maintainers: [novusnota/prism-ton](https://github.com/novusnota/prism-ton)
Resolves #767
=> feat: update Prism.js definitions of Tact and FunC for syntax highlighting

docs/develop/companies/auditors.mdx
Added TonBit to Security Assurance Providers
=> Added TonBit to Security Assurance Providers

docusaurus.config.js, i18n/zh-CN/docusaurus-plugin-content-docs/current/v3/documentation/faq.md
The new rules of @docusaurus/plugin-client-redirects break links. We have to at least put a file to trigger new mapping, I think.
preview:
https://ton-docs-git-docs-fix-townsquarexyz.vercel.app/mandarin/
fix #821
=> fix: Mandarin version build

docs/v3/guidelines/dapps/asset-processing/jettons.md
Added missing info from the https://github.com/ton-community/ton-docs/pull/553 merge and reworked some statements
=> #553 jettons

docs/v3/guidelines/ton-connect/frameworks/react.mdx
=> Fix wallet-list-2.json redirect

docs/v3/guidelines/dapps/apis-sdks/ton-http-apis.md
Adding QuickNode under the RPC Nodes section so devs can get more options and have access to QuickNode TON RPC API
=> Adding QuickNode as RPC node provider

docs/v3/guidelines/dapps/tutorials/mint-your-first-token.md
Added a link to the testnet version of TON Minter.
=> TON Minter testnet

docs/v3/guidelines/smart-contracts/howto/compile/compilation-instructions.md
Verification of compilation guidelines. Tested on official ubuntu-22.04 and 'latest' docker images.
IMAGE ID's:
59ab366372d5
97271d29cb79
=>  add liblz4-dev dependency

docusaurus.config.js, static/robots.txt
=> Add Algolia Search

docs/v3/documentation/smart-contracts/fift/overview.mdx, docs/v3/documentation/tvm/tvm-initialization.md, docs/v3/documentation/tvm/tvm-overview.mdx, src/pages/v3/documentation/tvm/instructions.mdx
These tools are very useful for developers and knowledge about them should be spread wide
=> Retracer&Debugger update

docs/v3/documentation/smart-contracts/transaction-fees/fees.md
It's better to have something to play with, to see that formula is really working like described.
=> Add basic fee Calc

docs/v3/documentation/smart-contracts/message-management/message-modes-cookbook.mdx, docs/v3/documentation/smart-contracts/transaction-fees/fees-low-level.md
Clarified and corrected outcome of using modes and flags.
Also added some tips.
=> Reworked msg modes

docs/v3/documentation/smart-contracts/func/docs/stdlib.mdx, docs/v3/documentation/smart-contracts/message-management/message-modes-cookbook.mdx
=> Corrections for msg modes 64

docs/v3/documentation/data-formats/tlb/msg-tlb.mdx
Because this is critical technical documentation and it contains typos
=> Fix typos in msg-tlb.mdx around external messages

cspell.json, docs/v3/guidelines/get-started-with-ton.mdx
- Add new [video](https://www.youtube.com/watch?v=mgVUY04I_3A) recorded by Vladimir Alefman
=> Reload new Onboarding Challenge Walkthrough Video

i18n/zh-CN/docusaurus-plugin-content-docs/current/v3/concepts/dive-into-ton/ton-blockchain/cells-as-data-storage.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/v3/documentation/smart-contracts/message-management/message-modes-cookbook.mdx
fix error image path to enable mandarine version
=> fix: image path

i18n/zh-CN/docusaurus-plugin-content-docs/current/v3/concepts/dive-into-ton/ton-blockchain/cells-as-data-storage.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/v3/documentation/smart-contracts/message-management/message-modes-cookbook.mdx
https://ton-docs-git-img-path-fix-townsquarexyz.vercel.app
=> Img path fix

docs/v3/documentation/smart-contracts/message-management/message-modes-cookbook.mdx
It is important for us to maintain a high level of translation quality.
#910
=> Proofreading of the message mode cookbook

.github/workflows/build-prod.yml
=> Update build-prod.yml workflow

docs/v3/guidelines/ton-connect/guidelines/preparing-messages.mdx
=> correct USDT calculation and markdown styling

redirects/redirects.json
Fix redirect for the Mytonctrl Alerting page.
=> fix_redirect

docs/v3/guidelines/smart-contracts/howto/multisig-js.md, docs/v3/guidelines/smart-contracts/howto/multisig.md
Pages are outdated and must be reworked using new V2 contract
=> Multisig page DANGER banner

docs/v3/documentation/smart-contracts/contracts-specs/wallet-contracts.md, docs/v3/documentation/smart-contracts/message-management/internal-messages.md
Moving known op-codes to Message management, md formatting.
=> MD Corrections & Op-code list transfer

docs/v3/guidelines/nodes/running-nodes/archive-node.md
#957
- A tip on how to delete snapshots has been added.
- Referenced https://archival-dump.ton.org/
=> Add info on ZFS dumps to archive-node.md

docs/v3/guidelines/nodes/persistent-states.md
Update persistent states blocks for 2025
Closes issue: https://github.com/ton-community/ton-docs/issues/974
=> Update persistent-states.md for 2025

docs/v3/guidelines/nodes/maintenance-guidelines/mytonctrl-private-alerting.md
=> update mtc alerting bot docs

docs/v3/guidelines/nodes/running-nodes/staking-with-nominator-pools.md
Rework and updates on https://docs.ton.org/v3/guidelines/nodes/running-nodes/staking-with-nominator-pools 
Closes https://github.com/ton-community/ton-docs/issues/1017
=> Nominator Pools rework and update 

docs/v3/documentation/smart-contracts/message-management/message-modes-cookbook.mdx, docs/v3/documentation/smart-contracts/message-management/sending-messages.md, docs/v3/guidelines/smart-contracts/security/things-to-focus.md
- Added general description
- Added links to relevant pages
Closes #1016 .
=> +2 flag update

docs/v3/guidelines/nodes/running-nodes/full-node.mdx
Proofreading and rework for the following:
https://docs.ton.org/v3/guidelines/nodes/running-nodes/full-node
Closes https://github.com/ton-community/ton-docs/issues/1032
=> Rework and proofread on full node

docs/v3/documentation/smart-contracts/contracts-specs/vesting-contract.mdx
Proofread & Rework on https://docs.ton.org/v3/documentation/smart-contracts/contracts-specs/vesting-contract 
Closes https://github.com/ton-community/ton-docs/issues/1037
=> Proofread & Rework || Vesting Contract

cspell.json, docs/v3/guidelines/nodes/running-nodes/liteserver-node.md, docs/v3/guidelines/nodes/running-nodes/run-mytonctrl-docker.md, docs/v3/guidelines/nodes/running-nodes/validator-node.md
Proofreading and rework || Update liteserver node, validator node and MyTonCtrl Docker installation guide
The reviewed pages:
- https://docs.ton.org/v3/guidelines/nodes/running-nodes/liteserver-node#interaction-with-liteserver-lite-client
- https://docs.ton.org/v3/guidelines/nodes/running-nodes/validator-node
- https://docs.ton.org/v3/guidelines/nodes/running-nodes/run-mytonctrl-docker
Closes https://github.com/ton-community/ton-docs/issues/1046
=> Proofreading & Rework || Update liteserver node, validator node and run MyTonCtrl Docker

docs/v3/guidelines/dapps/cookbook.mdx, docs/v3/guidelines/dapps/overview.mdx
=> Rework and proofread DApps Cookbook

docs/v3/guidelines/dapps/apis-sdks/api-keys.mdx, docs/v3/guidelines/dapps/apis-sdks/getblock-ton-api.md, docs/v3/guidelines/dapps/tutorials/mint-your-first-token.md, docs/v3/guidelines/dapps/tutorials/nft-minting-guide.md, docs/v3/guidelines/dapps/tutorials/web3-game-example.md, docs/v3/guidelines/dapps/tutorials/zero-knowledge-proofs.md
=> Rework and proofread Tutorials and Examples

docs/v3/guidelines/dapps/tma/tutorials/app-examples.mdx, docs/v3/guidelines/dapps/tma/tutorials/design-guidelines.mdx, docs/v3/guidelines/dapps/tma/tutorials/step-by-step-guide.mdx
=> Rework and proofread TMA Tutorials & Examples

docs/v3/guidelines/dapps/asset-processing/jettons.md, docs/v3/guidelines/dapps/asset-processing/mass-mint-tools.mdx, docs/v3/guidelines/dapps/asset-processing/mintless-jettons.mdx, docs/v3/guidelines/dapps/asset-processing/nft-processing/metadata-parsing.md, docs/v3/guidelines/dapps/asset-processing/nft-processing/nfts.md, docs/v3/guidelines/dapps/asset-processing/payments-processing.md
=> Rework and proofread Advanced Asset Processing

docs/v3/concepts/dive-into-ton/ton-ecosystem/explorers-in-ton.mdx
Update OKX explorer url in explorers-in-ton.mdx
Update OKX explorer url in explorers-in-ton.mdx
=> Update OKX explorer url

docs/v3/guidelines/dapps/apis-sdks/getblock-ton-api.md, docs/v3/guidelines/dapps/tutorials/jetton-airdrop.md, sidebars/guidelines.js
PR from Tonkeeper Team: added new guide about TON jetton distribution tool (https://tonapi.io/airdrop).
Closes - https://github.com/ton-community/ton-docs/issues/1057
=> Added new guide: how to launch a jetton airdrop

docs/v3/guidelines/web3/overview.mdx, docs/v3/guidelines/web3/ton-dns/dns.md, docs/v3/guidelines/web3/ton-dns/subresolvers.md, docs/v3/guidelines/web3/ton-proxy-sites/connect-with-ton-proxy.md, docs/v3/guidelines/web3/ton-proxy-sites/how-to-open-any-ton-site.md, docs/v3/guidelines/web3/ton-proxy-sites/how-to-run-ton-site.md, docs/v3/guidelines/web3/ton-proxy-sites/running-your-own-ton-proxy.md, docs/v3/guidelines/web3/ton-proxy-sites/site-and-domain-management.md, docs/v3/guidelines/web3/ton-proxy-sites/ton-sites-for-applications.mdx, docs/v3/guidelines/web3/ton-storage/storage-daemon.md, docs/v3/guidelines/web3/ton-storage/storage-faq.md, docs/v3/guidelines/web3/ton-storage/storage-provider.md
- https://docs.ton.org/v3/guidelines/web3/overview
- https://docs.ton.org/v3/guidelines/web3/ton-dns/dns
- https://docs.ton.org/v3/guidelines/web3/ton-dns/subresolvers
- https://docs.ton.org/v3/guidelines/web3/ton-proxy-sites/how-to-run-ton-site
- https://docs.ton.org/v3/guidelines/web3/ton-proxy-sites/ton-sites-for-applications
- https://docs.ton.org/v3/guidelines/web3/ton-proxy-sites/connect-with-ton-proxy
- https://docs.ton.org/v3/guidelines/web3/ton-proxy-sites/how-to-open-any-ton-site
- https://docs.ton.org/v3/guidelines/web3/ton-proxy-sites/site-and-domain-management
- https://docs.ton.org/v3/guidelines/web3/ton-proxy-sites/running-your-own-ton-proxy
- …
=> 1102-rework-proofread-web3-guidelines

docs/v3/guidelines/ton-connect/business/ton-connect-for-business.md, docs/v3/guidelines/ton-connect/business/ton-connect-for-security.md, docs/v3/guidelines/ton-connect/guidelines/creating-manifest.md, docs/v3/guidelines/ton-connect/guidelines/integration-with-javascript-sdk.md, docs/v3/guidelines/ton-connect/guidelines/preparing-messages.mdx, docs/v3/guidelines/ton-connect/guidelines/sending-messages.md, docs/v3/guidelines/ton-connect/guidelines/verifying-signed-in-users.mdx, redirects/redirects.json, sidebars/guidelines.js
- https://docs.ton.org/v3/guidelines/ton-connect/guidelines/creating-manifest
- https://docs.ton.org/v3/guidelines/ton-connect/guidelines/preparing-messages
- https://docs.ton.org/v3/guidelines/ton-connect/guidelines/sending-messages
- https://docs.ton.org/v3/guidelines/ton-connect/guidelines/verifying-signed-in-users
- https://docs.ton.org/v3/guidelines/ton-connect/guidelines/integration-with-javascript-sdk
- https://docs.ton.org/v3/guidelines/ton-connect/business/ton-connect-for-business
- https://docs.ton.org/v3/guidelines/ton-connect/business/ton-connect-for-security
Closes https://github.com/ton-community/ton-docs/issues/1069.
=> Rework and proofread Integrate with TON part 2 of 2

docs/v3/documentation/smart-contracts/contracts-specs/governance.md, docs/v3/documentation/smart-contracts/contracts-specs/nominator-pool.mdx, docs/v3/documentation/smart-contracts/contracts-specs/precompiled-contracts.md, docs/v3/documentation/smart-contracts/contracts-specs/single-nominator-pool.md, docs/v3/documentation/smart-contracts/message-management/messages-and-transactions.mdx
https://docs.ton.org/v3/documentation/smart-contracts/contracts-specs/governance
https://docs.ton.org/v3/documentation/smart-contracts/contracts-specs/nominator-pool
https://docs.ton.org/v3/documentation/smart-contracts/contracts-specs/single-nominator-pool
https://docs.ton.org/v3/documentation/smart-contracts/contracts-specs/precompiled-contracts
https://docs.ton.org/v3/documentation/smart-contracts/message-management/messages-and-transactions
Closes #1081.
=> Rework & proofread smart contract documentation #2

docs/v3/documentation/smart-contracts/message-management/ecosystem-messages-layout.mdx, docs/v3/documentation/smart-contracts/message-management/external-messages.md, docs/v3/documentation/smart-contracts/message-management/internal-messages.md, docs/v3/documentation/smart-contracts/message-management/message-modes-cookbook.mdx, docs/v3/documentation/smart-contracts/message-management/non-bounceable-messages.md, docs/v3/documentation/smart-contracts/message-management/sending-messages.md
https://docs.ton.org/v3/documentation/smart-contracts/message-management/sending-messages
https://docs.ton.org/v3/documentation/smart-contracts/message-management/internal-messages
https://docs.ton.org/v3/documentation/smart-contracts/message-management/external-messages
https://docs.ton.org/v3/documentation/smart-contracts/message-management/non-bounceable-messages
https://docs.ton.org/v3/documentation/smart-contracts/message-management/message-modes-cookbook
https://docs.ton.org/v3/documentation/smart-contracts/message-management/ecosystem-messages-layout
Closes #1083.
=> Rework & proofread smart contract documentation #3

src/components/Feedback/index.module.css, src/components/Feedback/index.tsx
Reverts ton-community/ton-docs#1117
=> Revert "fix: feedback buttons colour scheme on mobiles"

docs/v3/documentation/dapps/assets/overview.md, docs/v3/documentation/dapps/assets/usdt.md, docs/v3/documentation/dapps/dapps-overview.md, docs/v3/documentation/dapps/defi/nft.md, docs/v3/documentation/dapps/defi/subscriptions.md, docs/v3/documentation/dapps/defi/tokens.mdx, docs/v3/documentation/dapps/defi/ton-payments.md, docs/v3/documentation/dapps/oracles/about_blockchain_oracles.md, docs/v3/documentation/dapps/oracles/pyth.mdx, docs/v3/documentation/dapps/oracles/red_stone.mdx, docs/v3/documentation/faq.md, docs/v3/documentation/smart-contracts/addresses.md, docs/v3/documentation/smart-contracts/contracts-specs/examples.md, docs/v3/documentation/smart-contracts/contracts-specs/highload-wallet.md, docs/v3/documentation/smart-contracts/contracts-specs/wallet-contracts.md, docs/v3/guidelines/nodes/overview.md, docs/v3/guidelines/ton-connect/overview.mdx, navbar.js, sidebars/documentation.js
https://docs.ton.org/v3/documentation/dapps/defi/coins
https://docs.ton.org/v3/documentation/dapps/defi/tokens
https://docs.ton.org/v3/documentation/dapps/defi/nft
https://docs.ton.org/v3/documentation/dapps/defi/subscriptions
https://docs.ton.org/v3/documentation/dapps/defi/ton-payments
https://docs.ton.org/v3/documentation/dapps/assets/overview
https://docs.ton.org/v3/documentation/dapps/assets/usdt
https://docs.ton.org/v3/documentation/dapps/oracles/about_blockchain_oracles
https://docs.ton.org/v3/documentation/dapps/oracles/pyth
https://docs.ton.org/v3/documentation/dapps/oracles/red_stone
https://docs.ton.org/v3/guidelines/nodes/overview
Closes …
=> Rework DApps documentation

src/components/Feedback/index.module.css, src/components/Feedback/index.tsx
Fixing styles in the feedback component. These changes do not affect styles in the markdown pages, only in the component.
=> fix: button text color scheme

cspell.json, docs/v3/guidelines/nodes/running-nodes/archive-node.md, docs/v3/guidelines/nodes/running-nodes/full-node.mdx
Fix: update support contact information in node documentation:
- https://docs.ton.org/v3/guidelines/nodes/running-nodes/archive-node
- https://docs.ton.org/v3/guidelines/nodes/running-nodes/full-node
Closes https://github.com/ton-community/ton-docs/issues/1140 .
=> fix: update support contact information in node documentation

docs/v3/documentation/smart-contracts/getting-started/ide-plugins.md
=> Fix link to tact-language-server repository

docs/v3/documentation/smart-contracts/getting-started/ide-plugins.md
Added section with new Tact JetBrains plugin 
Closes #1159.
=> Add Tact plugin for JetBrains IDEs

docs/v3/concepts/dive-into-ton/go-from-ethereum/difference-of-blockchains.md, docs/v3/concepts/dive-into-ton/ton-blockchain/cells-as-data-storage.md, docs/v3/contribute/README.md, docs/v3/documentation/archive/tg-bot-integration.mdx, docs/v3/documentation/data-formats/tlb/proofs.mdx, docs/v3/documentation/data-formats/tlb/tl-b-language.mdx, docs/v3/documentation/infra/nodes/mytonctrl/mytonctrl-overview.mdx, docs/v3/documentation/smart-contracts/contracts-specs/wallet-contracts.md, docs/v3/documentation/tvm/tvm-exit-codes.md, docs/v3/guidelines/ton-connect/guidelines/preparing-messages.mdx
- https://github.com/ton-community/ton-docs/pull/1077
- https://github.com/ton-community/ton-docs/pull/1076
- https://github.com/ton-community/ton-docs/pull/1074
- https://github.com/ton-community/ton-docs/pull/1072
- https://github.com/ton-community/ton-docs/pull/1065
- https://github.com/ton-community/ton-docs/pull/952
- https://github.com/ton-community/ton-docs/pull/908
- https://github.com/ton-community/ton-docs/pull/898
- https://github.com/ton-community/ton-docs/pull/810
- https://github.com/ton-community/ton-docs/pull/802
Closes https://github.com/ton-community/ton-docs/issues/1173.
=> 1173 proofread and spelling fixess

docs/v3/documentation/smart-contracts/func/docs/literals_identifiers.md
Added an example of a multi-line expression and removed the previous text about it.
Closes #704.
=> (FunC) Add clarifications for literals and identifiers

docs/v3/documentation/smart-contracts/func/docs/global_variables.md
=> Add info about global variables limits in FunC 

docs/v3/documentation/smart-contracts/func/docs/types.md
Removed misleading info.
Closes #719.
=> Update types page

docs/v3/documentation/smart-contracts/func/docs/functions.md
=> Method ID clarifications

docs/v3/documentation/smart-contracts/limits.md
Links to source files and config parameters were added to the column `Defined in`
=> Update blockchain limits page

docs/v3/documentation/data-formats/tlb/tlb-ide.md
=> fix(tlb-ide): link to tlb-parser

README.md, docs/v3/guidelines/dapps/transaction-guideline.mdx
<--Brief description of the changes introduced in this pull request. Include any relevant issue numbers or links.-->
Closes <--link to issue]-->.
=> add_transaction_descr

docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-detail.mdx, docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/mutability.mdx, docs/v3/guidelines/dapps/apis-sdks/sdk.mdx
Closes (https://github.com/ton-community/ton-docs/issues/1275).
=> Headers updates

docs/v3/guidelines/dapps/transactions/api-based-retrieval.mdx, docs/v3/guidelines/dapps/transactions/explore-transactions.mdx
Updated: 
- API section
- minor upds: punctuation & wording 
Closes .
=> Updating Mastering transactios 

docs/v3/guidelines/ton-connect/frameworks/python.mdx, docs/v3/guidelines/ton-connect/guidelines/developers.mdx, docs/v3/guidelines/ton-connect/guidelines/preparing-messages.mdx, sidebars/guidelines.js
**Related to** [ton-society/grants-and-bounties#1112](https://github.com/ton-society/grants-and-bounties/issues/1112), which is currently under review.
The changes here are independent and useful on their own but align with the goals outlined in the bounty description.
**A Russian version** of the updated content is also available:
• Updated SDK list — [developers.md](https://github.com/nessshon/ton-docs/blob/tonconnect-update/i18n/ru/docusaurus-plugin-content-docs/current/v3/guidelines/ton-connect/guidelines/developers.md)
• Added full Python integration guide — [python.mdx](https://github.com/nessshon/ton-docs/blob/tonconnect-update/i18n/ru/docusaurus-plugin-content-docs/current/v3/guidelines/ton-connect/frameworks/python.mdx)
• Updated message preparation guide — …
=> Improve TON Connect Python integration docs

docs/v3/guidelines/ton-connect/guidelines/transaction-by-external-message.mdx, sidebars/guidelines.js
Description
This pull request adds a new article: Tracking external-in messages in TON.
The document explains how to find a transaction associated with an external-in message in the TON Blockchain.
It covers:
Message normalization according to TEP-467
Searching for a transaction by normalized message hash
Waiting for transaction confirmation
Example code for integration
Closes https://github.com/ton-community/ton-docs/issues/1329
=> docs: Tracking external-in messages in TON

docs/v3/guidelines/dapps/transactions/hash-based-tracking.mdx, docs/v3/guidelines/dapps/transactions/message-driven-execution.mdx, docs/v3/guidelines/smart-contracts/testing/blueprint-config.mdx, docs/v3/guidelines/ton-connect/guidelines/transaction-by-external-message.mdx
Redo code examples for the [hash-based-tracking](https://docs.ton.org/v3/guidelines/dapps/transactions/hash-based-tracking) page
=> Resolve inconsistency issues with the hash tracking transaction examples

docs/v3/documentation/infra/nodes/validation/collators.mdx, docs/v3/guidelines/nodes/running-nodes/collators-validators.mdx, sidebars/guidelines.js
<--Brief description of the changes introduced in this pull request. Include any relevant issue numbers or links.-->
Closes <--link to issue]-->.
=> update collator docs, add article about collators in mtc

docs/v3/documentation/smart-contracts/getting-started/ide-plugins.mdx, docs/v3/guidelines/dapps/apis-sdks/api-types.mdx, docs/v3/guidelines/dapps/apis-sdks/getblock-ton-api.mdx, docs/v3/guidelines/dapps/apis-sdks/overview.mdx, docs/v3/guidelines/dapps/apis-sdks/ton-adnl-apis.mdx, sidebars/guidelines.js
Updated the Blockchain API & IDE Plugins sections
- [] I have created an issue.
=> Updated the Blockchain API & IDE Plugins sections

docs/v3/concepts/dive-into-ton/go-from-ethereum/blockchain-services.mdx
This PR was generated from branch `split/ai-fixes-big-docs-v3-concepts-dive-into-ton-go-from-ethereum-blockchain-services.mdx` into `main`.
- M: `docs/v3/concepts/dive-into-ton/go-from-ethereum/blockchain-services.mdx`
- [18] Use "On Ethereum" and avoid "users use" repetition
- https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/concepts/dive-into-ton/go-from-ethereum/blockchain-services.mdx?plain=1#L7
- [19] Replace "Such a device"; remove article before TON DNS
- https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/concepts/dive-into-ton/go-from-ethereum/blockchain-services.mdx?plain=1#L9
- [20] Remove redundant "DNS system"
- …
=> Split: update docs/v3/concepts/dive-into-ton/go-from-ethereum/blockchain-services.mdx (from ai-fixes-big vs main)

cspell.json, docs/v3/concepts/dive-into-ton/ton-blockchain/accounts.mdx, docs/v3/concepts/dive-into-ton/ton-blockchain/cells-as-data-storage.mdx, docs/v3/concepts/dive-into-ton/ton-blockchain/sharding.mdx, docs/v3/concepts/dive-into-ton/ton-blockchain/smart-contract-addresses.mdx, docs/v3/concepts/glossary.mdx, docs/v3/documentation/data-formats/tlb/tl-b-language.mdx, docs/v3/documentation/data-formats/tlb/tlb-ide.mdx, docs/v3/documentation/smart-contracts/getting-started/ide-plugins.mdx, docs/v3/documentation/smart-contracts/limits.mdx, docs/v3/documentation/smart-contracts/overview.mdx, docs/v3/documentation/smart-contracts/shards/shards-intro.mdx, docs/v3/documentation/smart-contracts/tact.mdx, docs/v3/documentation/smart-contracts/transaction-fees/fees-low-level.mdx, docs/v3/guidelines/dapps/transactions/api-based-retrieval.mdx, docs/v3/guidelines/quick-start/developing-smart-contracts/setup-environment.mdx, sidebars/documentation.js
Update Concepts and refactor Tact
=> Update Concepts and refactor Tact 

docs/v3/guidelines/dapps/asset-processing/payments-processing.mdx
Improve documentation for wallet-specific deeplinks
=> add better description for deeplinks

docs/v3/contribute/style-guide.mdx
This PR was generated from branch `split/ai-fixes-big-docs-v3-contribute-style-guide.mdx` into `main`.
- M: `docs/v3/contribute/style-guide.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/contribute/style-guide.mdx?plain=1#L26
The subheading reads “Example individuals journeys:”; change it to “Example individual journeys:” (or “Example individuals’ journeys:”).
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/contribute/style-guide.mdx?plain=1#L42
Replace “integrating my project to TON” with “integrating my project with TON.”
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/con …
=> Split: update docs/v3/contribute/style-guide.mdx (from ai-fixes-big vs main)

docs/v3/guidelines/dapps/tma/guidelines/monetization.mdx
This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-dapps-tma-guidelines-monetization.mdx` into `main`.
- M: `docs/v3/guidelines/dapps/tma/guidelines/monetization.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/dapps/tma/guidelines/monetization.mdx?plain=1
The sentence “Wallets provide the interface to approving transactions securely store users’ cryptographic keys on their personal devices.” is ungrammatical; replace it with “Wallets provide user interfaces for approving transactions and securely store users’ cryptographic keys on their personal devices.”
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf …
=> Split: update docs/v3/guidelines/dapps/tma/guidelines/monetization.mdx (from ai-fixes-big vs main)

sidebars/documentation.js
Fix the sidebar for nodes.
Closes <--link to issue]-->.
=> Fix and update side bar for documentation/nodes

docs/v3/documentation/tvm/overview.mdx
=> Fix TVM Overview page

docs/v3/concepts/dive-into-ton/ton-blockchain/operations.mdx, sidebars/concepts.js
=> operations
