docs/learn/tvm-instructions/instructions.md

Adding equivalent for s[i] POP
I tried to understand from the description what opcode does, and interviewed several developers, we could not give a correct answer to this. So I'm adding an equivalent to make it easier to understand.

docs: adding equivalent for s[i] POP

---

docs/develop/dapps/tutorials/how-to-run-ton-site.md

Adding a mention that is possible to run TON Sites via docker.
This change in the documentation makes it easier to understand that the section on installing and running TON Sites from sources is an alternative way.

docs: adding a mention that is possible to run TON Sites via docker

---

docs/develop/func/compiler_directives.md

Fixed displays of ligatures in https://ton.org/docs/develop/func/compiler_directives articles for operators.
Made the sign ≤ to display it as <=, vice versa.

Updated ligatures for "more or equal" and "less or equal" signs.

---

docs/develop/func/stdlib.mdx

Replaces `ket_len` with `key_len`
Typo
https://github.com/ton-community/ton-docs/issues/89

Replaces `ket_len` with `key_len`. Closes #89

---

docs/learn/overviews/addresses.md

typo
there is a typo in this address

Typo of "test giver" base64 address in the addresses.md

---

docs/learn/overviews/addresses.md

Changed broken link to the correct one. Also using commit hash in the link instead of branch name to prevent this issue in the future.
commit where `crc32.kt` file's folder was changed
https://github.com/andreypfau/ton-kotlin/commit/9ddd3f954048429dd1586ed13bacee94b0b592e2

Broken example link in the addresses.md

---

docs/develop/howto/compile.md

One of core variables when compiling TON from sources did not revealed in the docs
Everytime when updating TON you may not have this variable and code will not compile
-

Add information about `openssl3.3` on MacOS Intel

---

docs/learn/overviews/tl-b-language.mdx

According to [the TL specification](https://core.telegram.org/mtproto/TL-combinators#conditional-fields) `flags . 0` means the bit at index 0 is set. 
That's how BlockInfo::unpack looks like
```c++
bool BlockInfo::unpack(vm::CellSlice& cs, BlockInfo::Record& data) const {
int prev_seq_no;
return cs.fetch_ulong(32) == 0x9bc7a987U
&& cs.fetch_uint_to(32, data.version)
&& cs.fetch_bool_to(data.not_master)
&& cs.fetch_bool_to(data.after_merge)
&& cs.fetch_bool_to(data.before_split)
&& cs.fetch_bool_to(data.after_split)
&& cs.fetch_bool_to(data.want_split)
&& cs.fetch_bool_to(data.want_merge)
&& cs.fetch_bool_to(data.key_block)
&& cs.fetch_bool_to(data.vert_seqno_incr)
&& cs.fetch_uint_to(8, data.flags)
&& data.flags <= 1
&& cs.fetch_uint_to(32, data.seq_no)
&& cs.fetch_uint_to(32, …
```

Fix explanation of TL-B conditional fields

---

.github/ISSUE_TEMPLATE/suggest_tutorial.yaml
CONTRIBUTING.md
docs/contribute/hacktoberfest/README.mdx
docs/develop/dapps/tutorials/accept-payments-in-a-telegram-bot-2.md
docs/develop/dapps/tutorials/accept-payments-in-a-telegram-bot-js.md
docs/develop/dapps/tutorials/jetton-minter.md
docs/develop/fift-and-tvm-assembly.md
docs/develop/onboarding-challenge.mdx
docs/develop/smart-contracts/fees.md
docs/develop/smart-contracts/sdk/toncli.md
docs/learn/services/sites-www-proxy.md
docs/participate/ton-storage/storage-daemon.md
docs/participate/ton-storage/storage-faq.md
docs/participate/ton-storage/storage-provider.md
i18n/ko/docusaurus-plugin-content-docs/current/contribute/hacktoberfest/README.mdx
i18n/ko/docusaurus-plugin-content-docs/current/develop/dapps/payment-processing/accept-payments-in-a-telegram-bot-2.md
i18n/ko/docusaurus-plugin-content-docs/current/develop/smart-contracts/fees.md
i18n/zh-Hant/docusaurus-plugin-content-docs/current/contribute/hacktoberfest/README.mdx
i18n/zh-Hant/docusaurus-plugin-content-docs/current/develop/dapps/tutorials/accept-payments-in-a-telegram-bot-2.md
i18n/zh-Hant/docusaurus-plugin-content-docs/current/develop/dapps/tutorials/accept-payments-in-a-telegram-bot-js.md
i18n/zh-Hant/docusaurus-plugin-content-docs/current/develop/dapps/tutorials/jetton-minter.md
i18n/zh-Hant/docusaurus-plugin-content-docs/current/develop/smart-contracts/fees.md
i18n/zh-Hant/docusaurus-plugin-content-docs/current/learn/services/sites-www-proxy.md

There were many absolute links like https://ton.org/docs/*****, or even some old legacy https://tonspace.co/****
I've replaced all of them with working relative links

Fix all links in docs

---

docs/develop/dapps/README.md
docs/develop/dapps/tonconnect/README.md
docs/develop/dapps/tonconnect/business.md
docs/develop/dapps/tonconnect/comparison.md
docs/develop/dapps/tonconnect/developers.md
docs/develop/dapps/tonconnect/security.md
sidebars.js

Moving Ton Connect documentation from https://tonkeeper.gitbook.io/ton-connect-2.0-guide-for-sdk/

add ton-connect docs

---

docs/develop/dapps/ton-connect/README.md
docs/develop/dapps/ton-connect/integration.md
sidebars.js

This is a tutorial, by following which users should be able to create an integration button in their web applications,
- working with any wallet supporting TON Connect 2.0 (preferably even ones that aren't ready at the moment of writing tutorial)
- supporting ton_proof (so that backend is able to check actual address ownership)
- following integration best practices.
https://github.com/ton-society/ton-footsteps/issues/123

Added an article "Integration manual" for TON Connect 2.0

---

docs/develop/data-formats/cell-boc.md
docs/develop/data-formats/tl-b.md
docs/develop/data-formats/tl.md
docs/develop/network/adnl-tcp.md
docs/develop/network/adnl-udp.md
docs/develop/network/dht.md
docs/develop/network/overlay.md
docs/develop/network/rldp.md
docs/learn/networking/low-level-adnl.md
docs/learn/networking/overlay-subnetworks.md
docs/learn/networking/rldp.md
docs/learn/networking/ton-dht.md
docs/learn/overviews/TL-B.md
docs/learn/overviews/cells.md
sidebars.js

Added documentation (with real examples) of TON network protocols, such as: ADNL UDP/TCP, RLDP, DHT, Overlays and more.
Also added description of data formats such as: BoC, Cell, Merkle Proofs
Information is based on the translated [ton-deep-doc](https://github.com/xssnick/ton-deep-doc) with some extensions and formatting.
https://github.com/ton-society/ton-footsteps/issues/128

Network and data formats documentation from ton-deep-doc

---

docs/develop/smart-contracts/sdk/toncli.md

Links to workflow runs are outdated. This patch changes them so they lead to the list of the latest releases.

Update links to builds in toncli docs

---

docs/develop/dapps/ton-connect/transactions.md
sidebars.js

Currently, documentation on ton.org describes only way to connect user to dApp, but not to do anything more. Sending transactions is the next logical step.
https://github.com/ton-society/ton-footsteps/issues/150

Added "Sending messages with TON Connect 2.0" article

---

docs/participate/nodes/collators.md

Simple fix. I have changed one command for start validator after update config.
If someone will copy sting one by one then make a mistake and won't be able to run validator

Update collators.md (one word change)

---

docs/develop/dapps/apis/adnl.md

I created SDK for .NET and want to add link to it.
There is no existing .NET SDKs, so having at least one is important.
There are no related issues (or I don't know about them).

Add .NET SDK link

---

docs/develop/dapps/ton-connect/tg-bot-integration.md
sidebars.js

Added a tutorial about integrating the TonConnect to a telegram bot
There are many examples of integrating Ton Connect into frontend applications ([ton-connect/demo-dapp](https://github.com/ton-connect/demo-dapp), [ton-connect/demo-dapp-with-react-ui](https://github.com/ton-connect/demo-dapp-with-react-ui)), as well as many examples of authorization on the backend through tone proof ([ton-connect/demo-dapp-backend](https://github.com/ton-connect/demo-dapp-backend)). However, there are no examples of working with Ton Connect for telegram bots (that is, examples when user sessions are stored and processed on the backend). When integrating the Ton Connect into a telegram bot, there are some difficulties: you need to manage user sessions and close unused connections to wallets. …

feat: tg bot integration manual added

---

docs/develop/smart-contracts/sdk/javascript.md

It is important because using the command without `@latest` could lead to people using severely outdated packages at one point

Update `npm create ton` command to include `@latest`

---

docs/develop/howto/faq.md

1. The contracts do not use any private keys for deployment.
2. Mentioned ton-solidity project.
3. Mentioned that wallets support sending several messages at once, allowing a mini-batch of outgoing messages.
4. Added Q+A about contract deletion.
5. Mentioned dton.io among RPC providers.

Fixed significant mistake in FAQ about contract deployment

---

docs/develop/dapps/tutorials/collection-minting.md

It's better to use buff.subarray instead of buff.slice
LSP не ругается

Buffer.slice is deprecated

---

docs/develop/dapps/README.md
docs/develop/dapps/apis/sdk.mdx
docs/develop/dapps/apis/toncenter.md
docs/develop/overview.mdx
sidebars.js

* The Open Network SDKs references are updated in the documentation.
* References in the docs are unified and lead to the https://docs.ton.org/develop/dapps/apis/sdk page.

Weekly update 28

---

docs/develop/data-formats/proofs.mdx

I've changed the library name so the old links are not work now

update links for py examples in proofs article

---

docs/develop/smart-contracts/compile/README.md

it should be written 'binary form' due to './wallet.cell' output but it's written 'fift'
It's considered a typo, it's not vital.

fix wrong word

---

docusaurus.config.js
prism-theme.js

A slightly tweaked code highlighting theme for Prism.js, based on the default theme of Docusaurus engine — Palenight.
It's clear now which colors are used for each particular token, as opposed to the previous situation where defaults were used implicitly, without any info in the ton-docs repo itself.
Made as a bonus to [TON Footstep 288](https://github.com/ton-society/ton-footsteps/issues/288). Details and reasoning were provided there: [comment](https://github.com/ton-society/ton-footsteps/issues/288#issuecomment-1700824860).

feat: Code blocks theme update

---

docs/develop/data-formats/cell-boc.mdx

Value of second cell is FF, not AA. That was cell `7[FE]` padded to FF.

Fix typo in cell serialization example

---

docs/participate/nft.md

Supplemented the article with information about the benefits of using NFT Tickets and Authorization token via NFT.
The NFT Use Cases article in TON Documentation does not cover the topics of Ticket as an NFT and Authorization token as an NFT as mentioned in the provided context. But there are great advantages behind these things.
Telegram: https://t.me/sun_rhythms

Missing NFT use cases in TON Documentation

---

docs/develop/get-started-with-ton.mdx

the original `JavaScript limitations` link can't switch correctly, fix it to the correct link
the original `JavaScript limitations` link in [Numerical Mining Data in a User-Friendly Format](https://docs.ton.org/develop/get-started-with-ton#numerical-mining-data-in-a-user-friendly-format) can't switch correctly

docs: update the `JavaScript limitations` link

---

docs/develop/data-formats/proofs.mdx

On page https://docs.ton.org/develop/data-formats/proofs#block-header url  https://github.com/yungwine/pytoniq/blob/master/pytoniq/proof/check_proof.py#L33 got 404

fix url example Python checking proof

---

docs/develop/dapps/asset-processing/jettons.md

I just linked Tontools(python) and Tonjs(js) examples on this page and the go and Tokenweb version was that
https://github.com/ton-community/ton-docs/issues/353 
My telegram ID: [MK_dir98](https://t.me/MK_dir98)

add more example links in jetton processing page

---

docs/develop/dapps/tutorials/collection-minting.md

update the toncenter api bot link in [Setup development environment](https://docs.ton.org/develop/dapps/tutorials/collection-minting#-setup-development-environment)
when I click  `@tontestnetapibot` and `@tonapibot` in [Setup development environment](https://docs.ton.org/develop/dapps/tutorials/collection-minting#-setup-development-environment) , they don't switch 
correctly. 
`@tontestnetapibot` may be banned, but I have checked the docs and find we can use `@tonapibot` to create testnet or mainnet API
refer link: https://toncenter.com/

docs: update the toncenter api bot link

---

docs/contribute/tutorials/guidelines.md

**Broken link!**
Broken link, `contribute/sample-tutorial`  was replaced by `contribute/tutorials/sample-tutorial`, so now the link works

fix broken link.md

---

docs/develop/dapps/tutorials/collection-minting.md

The docs miss the `transfer` function in `NftItem.ts` when I try to run  the tutorial code
add `transfer` function in [Transfer item](https://docs.ton.org/develop/dapps/tutorials/collection-minting#transfer-item) part
The docs miss the `transfer` function in `NftItem.ts` when I try to run  the tutorial code

docs: add `transfer` function

---

docs/develop/dapps/telegram-apps/app-examples.mdx

There's a mis-matched indent in github action workflow file, and would cause github action fail. Just make it to the correct indent.
Changing hardtab (maybe, just my assumption) to spaces to match the yaml indent syntax. Otherwise, github action would complaint with error:
```
Check failure on line 30 in .github/workflows/static.yml
GitHub Actions/ .github/workflows/static.yml
Invalid workflow file
You have an error in your yaml syntax on line 30
```

fix: error with github action syntax caused with mis-matched indent

---

src/theme/prism/prism-tact.js

A foresight of upcoming Tact updates:
- binary (0b...) and octal (0o...) digits, https://github.com/tact-lang/tact/pull/87
- augmented assignments (+=, -=, *=, /=, %=), https://github.com/tact-lang/tact/pull/99
And a fix for `@interface("...")` feature, see [this question in Tact lang repo](https://github.com/tact-lang/tact/issues/112) to learn more.

feat: Prism.js update of Tact syntax highlighting

---

docs/develop/fift/overview.mdx
docs/develop/func/stdlib.mdx
docs/develop/smart-contracts/tutorials/wallet.md
docs/learn/docs.md
docs/learn/tvm-instructions/tvm-overview.md
docs/learn/tvm-instructions/tvm-upgrade-2023-07.md
docs/participate/wallets/apps.mdx
docusaurus.config.js
src/pages/learn/archive/tvm-instructions.mdx
src/pages/learn/tvm-instructions/instructions.mdx
src/pages/learn/tvm-instructions/instructions/app-specific.mdx
src/pages/learn/tvm-instructions/instructions/arithmetic.mdx
src/pages/learn/tvm-instructions/instructions/cell-manipulation.mdx
src/pages/learn/tvm-instructions/instructions/constant.mdx
src/pages/learn/tvm-instructions/instructions/control-flow.mdx
src/pages/learn/tvm-instructions/instructions/data-comparison.mdx
src/pages/learn/tvm-instructions/instructions/dictionary-manipulation.mdx
src/pages/learn/tvm-instructions/instructions/exception-gen-and-handling.mdx
src/pages/learn/tvm-instructions/instructions/miscellaneous.mdx
src/pages/learn/tvm-instructions/instructions/stack-manipulation.mdx
src/pages/learn/tvm-instructions/instructions/tuple-list-null.mdx

- TVM Instruction page updates
- Minor fixes and improvements

Weekly update 24-4

---

docs/learn/docs.md

Currently, Ton White paper only has the Traditional Chinese version, For developers in the Chinese Mainland, simplified Chinese is used. Traditional Chinese and simplified Chinese are very different in many places.  
So I spent almost one month translating Ton's white paper into the Simplified Chinese version(I checked every word and sentence to ensure better translation), which will be convenient for people using Simplified Chinese to read it.
I add a  link and description of the simplified Chinese version under the Traditional Chinese version on the Ton white paper - Overview page.
None

Added Simplified Chinese version for Ton white paper translation

---

docs/learn/tvm-instructions/instructions.csv
src/components/SearchField/index.tsx
src/data/opcodes/continuation.json
src/data/opcodes/opcodes.json
src/pages/learn/archive/tvm-instructions.mdx
src/pages/learn/tvm-instructions/instructions.mdx
src/pages/learn/tvm-instructions/instructions/app-specific.mdx
src/pages/learn/tvm-instructions/instructions/arithmetic.mdx
src/pages/learn/tvm-instructions/instructions/cell-manipulation.mdx
src/pages/learn/tvm-instructions/instructions/constant.mdx
src/pages/learn/tvm-instructions/instructions/control-flow.mdx
src/pages/learn/tvm-instructions/instructions/data-comparison.mdx
src/pages/learn/tvm-instructions/instructions/dictionary-manipulation.mdx
src/pages/learn/tvm-instructions/instructions/exception-gen-and-handling.mdx
src/pages/learn/tvm-instructions/instructions/miscellaneous.mdx
src/pages/learn/tvm-instructions/instructions/stack-manipulation.mdx
src/pages/learn/tvm-instructions/instructions/tuple-list-null.mdx

Replace `isGrouped` with `hasMarkdown` for `showKeys` items in SearchField. Fix typos in `SETALTCTR` and `SAVEBOTHCTR` opcodes description. Dynamic table layout in `SearchField`

SearchField hasMarkdown instead of isGrouped, dynamic table layout, fix typos

---

docs/develop/dapps/tutorials/collection-minting.md

Fixes URL protocol from `https:/example.com` to `https://example.com`.
Links on production navigate to 404 pages.
1. See [NFT guide page](https://docs.ton.org/develop/dapps/tutorials/collection-minting#about-the-author);
2. Try to navigate to any of updated links (eg. [GetGems NFT-contracts](https://docs.ton.org/github.com/getgems-io/nft-contracts)).
#468

fix url protocol

---

docs/develop/dapps/tutorials/collection-minting.md

Because NFT deploy instruction is broken

Fix links in NFT deploy instruction

---

docs/learn/tvm-instructions/instructions.csv

Typo in GASCONSUMED opcode: actual prefix is F807, not F802 ([tvm source](https://github.com/ton-blockchain/ton/blob/692211fe9100edef48b8ab7764defeb3da36f475/crypto/vm/tonops.cpp#L109)).

Fix GASCONSUMED opcode

---

src/data/opcodes/app_specific.json
src/data/opcodes/cell_manipulation.json
src/data/opcodes/opcodes.json

Added and distributed new TVM opcodes from the [2024.04 TVM Upgrade](https://docs.ton.org/learn/tvm-instructions/fee-calculation-instructions). 
Developer as a part of https://github.com/ton-society/grants-and-bounties/issues/501

Add and distribute new TVM opcodes

---

i18n/zh-Hans/docusaurus-plugin-content-pages/learn/archive/tvm-instructions.mdx
i18n/zh-Hans/docusaurus-plugin-content-pages/learn/tvm-instructions/instructions.mdx
i18n/zh-Hans/docusaurus-plugin-content-pages/learn/tvm-instructions/instructions/app-specific.mdx
i18n/zh-Hans/docusaurus-plugin-content-pages/learn/tvm-instructions/instructions/arithmetic.mdx
i18n/zh-Hans/docusaurus-plugin-content-pages/learn/tvm-instructions/instructions/cell-manipulation.mdx
i18n/zh-Hans/docusaurus-plugin-content-pages/learn/tvm-instructions/instructions/constant.mdx
i18n/zh-Hans/docusaurus-plugin-content-pages/learn/tvm-instructions/instructions/control-flow.mdx
i18n/zh-Hans/docusaurus-plugin-content-pages/learn/tvm-instructions/instructions/data-comparison.mdx
i18n/zh-Hans/docusaurus-plugin-content-pages/learn/tvm-instructions/instructions/dictionary-manipulation.mdx
i18n/zh-Hans/docusaurus-plugin-content-pages/learn/tvm-instructions/instructions/exception-gen-and-handling.mdx
i18n/zh-Hans/docusaurus-plugin-content-pages/learn/tvm-instructions/instructions/miscellaneous.mdx
i18n/zh-Hans/docusaurus-plugin-content-pages/learn/tvm-instructions/instructions/stack-manipulation.mdx
i18n/zh-Hans/docusaurus-plugin-content-pages/learn/tvm-instructions/instructions/tuple-list-null.mdx

The current https://docs.ton.org/zh-Hans/learn/tvm-instructions/instructions page crashes due to the Mandarin translation is based on a earlier version TON docs with outdated `searchBy` key.
https://github.com/ton-community/ton-docs/issues/509

fix instructions page crash due to outdated searchBy key

---

docs/develop/dapps/cookbook.md
docs/develop/func/cookbook.md

1. Fixing spelling mistake `dosen't` --> `doesn't`, as described in #508 
2. Fixing `crypt` to `crypto` installation instructions. (Otherwise, the commands fail).
3. Filling in a TODO for linking to Random Number generation article.
#508

Fix spelling mistakes RE: #508 & Extra

---

docs/develop/dapps/asset-processing/README.md

Removed not working nft invoice.
Added toncoin invoice.
Added example of ton link generation

improve ton link invoices block

---

docs/develop/howto/fees-low-level.md
docs/develop/overview.mdx
docs/develop/smart-contracts/fees.md
docs/develop/smart-contracts/tutorials/wallet.md

Rework fees articles

---

docs/develop/dapps/apis/sdk.mdx

The correct name for the java library is `ton4j`.

Fix typo in docs

---

docs/develop/func/stdlib.mdx

Update flag info from https://github.com/ton-community/ton-docs/pull/544#issue-2260817530
[569](https://github.com/ton-community/ton-docs/issues/569#issue-2280700097)

update func docs: update +2 flag info

---

docs/develop/dapps/asset-processing/usdt.md
sidebars.js

Add USDT info section 

---

docs/develop/func/cookbook.md
docs/develop/howto/faq.md

[#593](https://github.com/ton-community/ton-docs/issues/593)

Added information about upgradable smart-contracts and an example

---

docs/develop/func/dictionaries.md
sidebars.js

This article makes it written knowledge that dictionaries can have limited amount of key-value pairs and tend to make contract run out of gas if a large number of updates is made. Article also gives some information about other types of maps (according to other information sources available; prefix dictionaries don't have any, and trying to reverse-engineer them has an inconclusive results).
https://github.com/ton-society/grants-and-bounties/issues/455

Created article about dictionaries

---

docs/develop/dapps/telegram-apps/testing-apps.mdx

Instructions were outdated
- Beta no longer needed
- macOS is supported

Update instructions how to access web console in Telegram desktop

---

docs/develop/smart-contracts/messages.md

Add note about bounceable message explanation
[591](https://github.com/ton-community/ton-docs/issues/591)

add phases execution flow explanation

---

docs/develop/dapps/ton-connect/sign.mdx

Add js ton_proof demo

---

docs/participate/wallets/contracts.md

[#608](https://github.com/ton-community/ton-docs/issues/608)

Added info about Wallet V5

---

docs/develop/dapps/apis/sdk.mdx

Adding Foton to the list of SDKs

---

docs/participate/wallets/contracts.md

Endpoint for Wallet V5

---

docs/develop/func/stdlib.mdx
docs/develop/smart-contracts/messages.md

Sendmode example

---

docs/develop/oracles/red_stone.mdx

Just added one missed link to https://github.com/redstone-finance/redstone-oracles-monorepo

Missing full link in red_stone.mdx for price_manager.fc

---

docs/participate/web3/how-to-open-any-ton-site.md
docs/participate/web3/setting-proxy.md
docs/participate/web3/sites-and-proxy.md
sidebars.js

- participate/web3/sites-and-proxy
- public proxy
PP are obsolete, GO is preferred method for TON Sites and Proxies

Delete public proxy and C++ compile page

---

docs/participate/run-nodes/archive-node.md

Add link for testnet dump for archive node

---

docs/develop/dapps/asset-processing/overview.md
docs/develop/data-formats/tl-b-language.mdx
docs/develop/data-formats/tlb-ide.md
docs/develop/data-formats/tlb-parsers.md
docs/develop/data-formats/tlb-tools.md
sidebars.js

Add tlb codegen link

---

docs/develop/dapps/cookbook.mdx

The **tonutils-go** library now supports parsing raw addresses out of the box, there is no need to implement this by hand. I updated the cookbook example accordingly. Also, the `printRawAddr` function was renamed to `rawAddr` since it doesn't actually print anything.
Cookbook entries should be up to date and avoid unnecessary complexity.
None

Update Go example in "How to convert" section of the "Working with contracts' addresses" chapter of the cookbook

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/develop/smart-contracts/messages.md

fix i18n link
the link is https://docs.ton.org/mandarin/learn/tvm-instructions/tvm-overview.md now, but it should be "https://docs.ton.org/mandarin/learn/tvm-instructions/tvm-overview"

:bug: Fix link in doc

---

docs/participate/network-maintenance/staking-incentives.md

Add some explanation for effective stake

---

docs/participate/wallets/apps.mdx

feat: upd wallets switch testnet info

---

docs/develop/smart-contracts/messages.md

Fix token calculation shown in sending_message mode.
This is a non-trivial typo as developer most likely refer to mode 0 to understand how token transfer works

Fix typo in mode 0 of send_raw_message

---

docs/develop/dapps/ton-connect/message-builders.mdx
package-lock.json

Update GetGems NFT sale code for compatibility with v3r3 smart contract
This pull request updates the NFT sale code to work with the latest GetGems smart contract (v3r3). The previous version (v3r2) is no longer compatible.
Changes:
• Updated code for NFT sale functionality on all three supported languages (Python, JS, and Go) to work with the new v3r3 smart contract.
• Tested code thoroughly for Python and JS. Go code has not been tested, but I think it works well.
• Minor code clean-up and refactoring in other areas of the repository.
Benefits:
• Improved compatibility with the latest GetGems smart contract.
• Ensures smooth operation of the NFT sale process for users.
Link: https://docs.ton.org/develop/dapps/ton-connect/message-builders#nft-sale-getgems

Fixed code for selling nft on getgems

---

docs/participate/run-nodes/archive-node.md
docs/participate/run-nodes/nodes-troubleshooting.md

Update data about archive node sync timings

---

docs/develop/smart-contracts/guidelines/message-delivery-guarantees.mdx
docs/learn/tvm-instructions/tvm-overview.mdx

Added definition of success for transaction and some details for TVM execution
There should be information about what called succeed transaction

Transaction outcome description

---

docs/develop/dapps/asset-processing/usdt.md

and open external links to bridge.ton.org and tether.io in new page
Fixes a link to bridge.ton.org that is broken because it winds up as a relative (an uncle instead of a brother... lol)
The default web rule is to open new tabs on external links. - This has bee like that even in 2012...
See https://uxmovement.com/navigation/why-external-links-should-open-in-new-tabs/
I thought TON was supposed to advance the web, not make it worse... (no hate, though)

fix bridge.ton.org link 

---

docs/develop/dapps/apis/toncenter.md

Adding Tatum under RPC Nodes provider as Tatum provides TON RPC Nodes and whole infrastructure to run Web3 Apps.
Adding Tatum under RPC Nodes provider since Tatum provides TON RPC nodes
Adding Tatum under Nodes provider as another provider of TON rpc nodes

Adding Tatum under RPC Nodes provider

---

docs/participate/run-nodes/enable-liteserver-node.md
docs/participate/run-nodes/mytonctrl.mdx

Add information about configs

---

docs/develop/dapps/apis/README.md

Replaced the link to a specific endpoint with a link to the relevant page in the tonapi documentation
This provides better context and comprehensive information compared to just an endpoint.

change link to tonapi rates documentarion

---

docs/develop/dapps/asset-processing/README.md
docs/develop/dapps/asset-processing/jettons.md

improve transaction processing

---

docs/develop/dapps/asset-processing/jettons.md

fix jetton sample

---

docs/participate/nodes/node-types.md

Link "Running a validator node" redirects to /enable-liteserver-node

Fix a tiny typo

---

docs/develop/dapps/ton-connect/sign.mdx

I have developed a [library for verifying ton_proof](https://github.com/WinoGarcia/TonProof.NET) in .NET. This [NuGet package](https://www.nuget.org/packages/TonProof) is production-ready.
I want to add it to the documentation. The repository has a [demo project](https://github.com/WinoGarcia/TonProof.NET?tab=readme-ov-file#usage) with usage examples.
Resolves #722

Add .NET ton_proof demo

---

docs/develop/dapps/apis/toncenter.md

Adding Chainstack as the RPC nodes (v2) & indexer provider (v3) to the list of TON node providers.

Add Chainstack as node & indexer provider

---

docs/develop/dapps/cookbook.mdx

https://github.com/ton-blockchain/wallet-contract-v5/blob/88557ebc33047a95207f6e47ac8aadb102dff744/contracts/wallet_v5.fc#L82
Transfer will fail without IGNORE_ERRORS flag with 137 exit code

Fix transfer example for V5R1 wallet

---

docs/participate/nodes/node-types.md

This refactoring makes the page about node types more consistent and readable. It now may serve as a basis for the entire section underneath (to be delivered in next PRs if this one is approved).

Refactored page about node types

---

docs/v3/documentation/faq.md
docs/v3/documentation/smart-contracts/getting-started/testnet.md
docs/v3/guidelines/dapps/apis-sdks/api-types.md
docs/v3/guidelines/dapps/apis-sdks/sdk.mdx
docs/v3/guidelines/dapps/apis-sdks/ton-http-apis.md

- Added **TONX API Testnet Faucet** link to the [Getting Started with Testnet](https://docs.ton.org/v3/documentation/smart-contracts/getting-started/testnet) page:  
- [TONX API Testnet Faucet](https://faucet.tonxapi.com/)  
- [Testnet TON Center API](https://testnet-rpc.tonxapi.com/)
- Updated the **APIs & SDKs** page to highlight TONX API:
- **RPC Nodes** section: Added mention of **TONX API** supernode for unmatched stability and low latency for TON DApps.  
- **Indexer** section: Added information about **TONX API**'s ability to list and filter on-chain data (Jetton, NFTs, and TON transactions) from the first block in a customized manner.  
- **Other APIs** section: Described **TONX API** as the go-to solution for accessing data on accounts, transactions, blocks, NFTs, and Jettons …

Update TON Documentation to Include TONX API Information Across Multiple Sections

---

docs/v3/guidelines/dapps/cookbook.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/develop/dapps/cookbook.md

Some of the Python examples currently fail to close the client due to a wrong variable name.
It causes exception and the provider is left open.
The fix allows to close the provider and avoid the exception.
In addition, standardizing indentation from tabs to spaces.
Currently, mixed indentation causes some examples to break.

fix: Python examples - provider close

---

docs/v3/documentation/data-formats/tlb/msg-tlb.mdx

`addr_std` is an internal address, but the description says it is an external address, which may cause confusion.

fix: typos in `addr_std$10` description

---

docs/v3/documentation/smart-contracts/getting-started/testnet.md
docs/v3/guidelines/dapps/apis-sdks/api-types.md
docs/v3/guidelines/dapps/apis-sdks/getblock-ton-api.md
docs/v3/guidelines/dapps/apis-sdks/overview.md
docs/v3/guidelines/dapps/apis-sdks/ton-adnl-apis.md
docs/v3/guidelines/dapps/apis-sdks/ton-http-apis.md

- Added Testnet Services Links for https://docs.ton.org/v3/documentation/smart-contracts/getting-started/testnet
- Highlighted TON Infrusrtucture dashboards for API and Nodes Monitor

Extend testnet links

---

docs/v3/documentation/smart-contracts/message-management/message-modes-cookbook.mdx

Corrections for msg mode cookbook

---

docs/v3/concepts/qa-outsource/auditors.mdx
docs/v3/concepts/qa-outsource/outsource.mdx
docs/v3/contribute/README.md
docs/v3/contribute/content-standardization.mdx
docs/v3/guidelines/ton-connect/frameworks/web.mdx
navbar.js
redirects/redirects.json
sidebars/concepts.js

Weekly fixes and minor updates
Closes: https://github.com/ton-community/ton-docs/issues/969

Weekly fixes and minor updates

---

docs/v3/documentation/smart-contracts/message-management/message-modes-cookbook.mdx
docs/v3/documentation/tvm/tvm-exit-codes.md
docs/v3/guidelines/nodes/running-nodes/archive-node.md

Refactor message modes cookbook and TVM exit codes documentation

---

docs/v3/concepts/dive-into-ton/ton-ecosystem/explorers-in-ton.mdx

The OKX TON Explorer is a powerful and user-friendly tool designed to provide comprehensive data insights into the TON (The Open Network) blockchain. It supports features such as address data, Jetton analysis, and NFT collection analysis, TON DNS, making it a valuable resource for both beginners and developers. By adding it to the list of third-party block explorers in the official documentation, users will have access to a broader range of tools to explore and interact with the TON ecosystem.
Add OKX TON Explorer introduction in [Explorers in TON](https://docs.ton.org/v3/concepts/dive-into-ton/ton-ecosystem/explorers-in-ton#crosschain-explorers)
Closes issue: https://github.com/ton-community/ton-docs/issues/995

OKX TON Explorer.mdx

---

docs/v3/documentation/smart-contracts/tolk/changelog.md
docs/v3/documentation/smart-contracts/tolk/overview.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-detail.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-short.md
src/theme/prism/prism-tolk.js

Update documentation for Tolk Language according to changes in Tolk v0.9.
Main PR to ton-blockchain: https://github.com/ton-blockchain/ton/pull/1545
Closes #992
1. Nullable types `int?`, `cell?`, etc.; null safety
2. Standard library (asm definitions) updated to reflect nullability
3. Smart casts, like in TypeScript in Kotlin
4. Operator `!` (non-null assertion)
5. Code after `throw` is treated unreachable
6. The `never` type

Update docs for Tolk v0.9

---

docs/v3/guidelines/smart-contracts/fee-calculation.md
docs/v3/guidelines/smart-contracts/get-methods.md
docs/v3/guidelines/smart-contracts/howto/wallet.md

https://docs.ton.org/v3/guidelines/smart-contracts/get-methods
https://docs.ton.org/v3/guidelines/smart-contracts/fee-calculation
https://docs.ton.org/v3/guidelines/smart-contracts/howto/wallet
#978

Smart contract guidelines proofread and rework 1

---

docs/v3/documentation/smart-contracts/tolk/changelog.md
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-detail.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-short.md
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/stdlib.md

Update documentation for Tolk Language according to changes in Tolk v0.10.
Main PR to ton-blockchain: https://github.com/ton-blockchain/ton/pull/1559
Closes #1039
1. Fixed-size integer types: `int32`, `uint64`, etc.
2. Type `coins` and function `ton("0.05")`
3. Types `bytesN` and `bitsN` (backed by slices at TVM level)
4. Replace `"..."c` postfixes with `stringCrc32("...")` functions
5. Support `0b...` number literals along with `0x...`
6. Trailing comma support

Update docs for Tolk v0.10

---

docs/v3/documentation/smart-contracts/tolk/changelog.md
docs/v3/documentation/smart-contracts/tolk/overview.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-detail.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-short.md
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/mutability.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/stdlib.md

- https://docs.ton.org/v3/documentation/smart-contracts/tolk/overview
- https://docs.ton.org/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-short
- https://docs.ton.org/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-detail
- https://docs.ton.org/v3/documentation/smart-contracts/tolk/tolk-vs-func/mutability
- https://docs.ton.org/v3/documentation/smart-contracts/tolk/tolk-vs-func/stdlib
- https://docs.ton.org/v3/documentation/smart-contracts/tolk/changelog
Closes issue: https://github.com/ton-community/ton-docs/issues/1055

Rework and proofread Tolk section

---

docs/v3/guidelines/dapps/tutorials/telegram-bot-examples/accept-payments-in-a-telegram-bot-2.md
docs/v3/guidelines/dapps/tutorials/telegram-bot-examples/accept-payments-in-a-telegram-bot-js.md
docs/v3/guidelines/dapps/tutorials/telegram-bot-examples/accept-payments-in-a-telegram-bot.md

Rework and proofread Telegram Bot Examples

---

docs/v3/guidelines/dapps/apis-sdks/api-types.md
docs/v3/guidelines/dapps/apis-sdks/overview.md
docs/v3/guidelines/dapps/apis-sdks/sdk.mdx
docs/v3/guidelines/dapps/apis-sdks/ton-adnl-apis.md
docs/v3/guidelines/dapps/apis-sdks/ton-http-apis.md

Rework and proofread APIs and SDKs

---

docs/v3/guidelines/dapps/tma/grants.mdx
docs/v3/guidelines/dapps/tma/guidelines/monetization.mdx
docs/v3/guidelines/dapps/tma/guidelines/publishing.mdx
docs/v3/guidelines/dapps/tma/guidelines/testing-apps.mdx
docs/v3/guidelines/dapps/tma/guidelines/tips-and-tricks.mdx
docs/v3/guidelines/dapps/tma/notcoin.mdx
docs/v3/guidelines/dapps/tma/overview.mdx

Rework and proofread Telegram Mini Apps & Guidelines

---

cspell.json
docs/v3/documentation/smart-contracts/fift/fift-and-tvm-assembly.md
docs/v3/documentation/smart-contracts/fift/fift-deep-dive.md
docs/v3/documentation/smart-contracts/fift/overview.mdx
docs/v3/documentation/tvm/tvm-initialization.md
docs/v3/documentation/tvm/tvm-overview.mdx

Style and grammatic checks for improved readability and formatting.
https://docs.ton.org/v3/documentation/tvm/tvm-initialization
https://docs.ton.org/v3/documentation/tvm/tvm-overview
https://docs.ton.org/v3/documentation/smart-contracts/fift/overview
https://docs.ton.org/v3/documentation/smart-contracts/fift/fift-and-tvm-assembly
https://docs.ton.org/v3/documentation/smart-contracts/fift/fift-deep-dive
Closes #1052.

Proofread TVM overview

---

docusaurus.config.js

Add Ru in menu without env config
Closes issue: https://github.com/ton-community/ton-docs/issues/1098

docs: add Russian language in menu

---

docs/v3/documentation/smart-contracts/tolk/changelog.md
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-detail.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-short.md
src/theme/prism/prism-tolk.js

Update documentation for Tolk Language according to changes in Tolk v0.11.
- https://github.com/ton-blockchain/ton/pull/1610
Closes #1094
Notable changes in Tolk v0.11:
1. Type aliases `type NewName = <existing type>`
2. Union types `T1 | T2 | ...`
3. Pattern matching for types
4. Operators `is` and `!is`
5. Pattern matching for expressions
6. Semicolon for the last statement in a block can be omitted

Update docs for Tolk v0.11

---

cspell.json
docs/v3/documentation/infra/crosschain/bridge-addresses.md
docs/v3/documentation/infra/crosschain/overview.md
docs/v3/documentation/infra/minter-flow.md
docs/v3/documentation/network/configs/blockchain-configs.md
docs/v3/documentation/network/configs/config-params.md
docs/v3/documentation/network/configs/network-configs.md
docs/v3/documentation/network/protocols/adnl/adnl-tcp.md
docs/v3/documentation/network/protocols/adnl/adnl-udp.md
docs/v3/documentation/network/protocols/adnl/low-level-adnl.md
docs/v3/documentation/network/protocols/adnl/overview.md
docs/v3/documentation/network/protocols/dht/dht-deep-dive.md
docs/v3/documentation/network/protocols/dht/ton-dht.md
docs/v3/documentation/network/protocols/overlay.md
docs/v3/documentation/network/protocols/rldp.md

Formatting and proofreading according to [documentation standards](https://docs.ton.org/v3/contribute) :
* https://docs.ton.org/v3/documentation/infra/minter-flow
* https://docs.ton.org/v3/documentation/infra/crosschain/overview
* https://docs.ton.org/v3/documentation/network/configs/blockchain-configs
* https://docs.ton.org/v3/documentation/network/configs/network-configs
* https://docs.ton.org/v3/documentation/infra/crosschain/bridge-addresses
* https://docs.ton.org/v3/documentation/network/configs/config-params
* https://docs.ton.org/v3/documentation/network/protocols/adnl/overview
* https://docs.ton.org/v3/documentation/network/protocols/adnl/low-level-adnl
* https://docs.ton.org/v3/documentation/network/protocols/adnl/adnl-tcp
* …

Rework & proofread Infra docs #2

---

docs/v3/documentation/smart-contracts/overview.mdx
docs/v3/documentation/smart-contracts/tact.mdx
i18n/ru/docusaurus-plugin-content-docs/current/v3/documentation/smart-contracts/overview.mdx
i18n/zh-CN/docusaurus-plugin-content-docs/current/v3/documentation/smart-contracts/overview.mdx
package.json
sidebars/documentation.js

Towards #983 — adds more visibility for Tact, but doesn't cover [Blueprint SDK](https://docs.ton.org/v3/documentation/smart-contracts/getting-started/javascript), [IDE Plugins](https://docs.ton.org/v3/documentation/smart-contracts/getting-started/ide-plugins), and other pages.

feat: add standalone page for Tact

---

docs/v3/documentation/smart-contracts/getting-started/ide-plugins.md
docs/v3/documentation/smart-contracts/getting-started/javascript.mdx
docs/v3/documentation/smart-contracts/overview.mdx
docs/v3/guidelines/dapps/tma/notcoin.mdx
docusaurus.config.js
i18n/ru/docusaurus-plugin-content-docs/current/v3/documentation/smart-contracts/overview.mdx

A follow-up to #1124, which closes #983.
* Updated the Blueprint page
* Updated the IDE plugins page with Tact tools, and added a link to TON Web IDE (https://ide.ton.org)
* Added links to TON development tutorials from `@alefmanvladimir`
As a small bonus I've also resolved a couple of warnings and enabled syntax highlighting of triple-ticked code blocks with "bash", "sh", and "shell" suffixes.

feat: descriptions of Tact plugins and tutorials

---

cspell.json
docs/v3/guidelines/dapps/apis-sdks/api-keys.mdx
docs/v3/guidelines/dapps/apis-sdks/api-types.md
docs/v3/guidelines/dapps/apis-sdks/ton-http-apis.md
docs/v3/guidelines/dapps/asset-processing/jettons.md
docs/v3/guidelines/dapps/asset-processing/nft-processing/nfts.md
docs/v3/guidelines/dapps/tutorials/nft-minting-guide.md
docs/v3/guidelines/smart-contracts/howto/single-nominator-pool.mdx

Fix : from Toncenter -> TON Center accross the whole documentation
Closes https://github.com/ton-community/ton-docs/issues/1137

fix: standardize "Toncenter" to "TON Center" across documentation

---

cspell.json
docs/v3/documentation/smart-contracts/tolk/changelog.md
docs/v3/documentation/smart-contracts/tolk/overview.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-detail.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-short.md
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/mutability.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/stdlib.md
src/theme/prism/prism-tolk.js

Update documentation for Tolk Language according to changes in Tolk v0.12.
* https://github.com/ton-blockchain/ton/pull/1645
1. Structures – named data representations, replacing raw tensors
2. Generics – reusable, type-safe abstractions
3. Methods — extension functions for any custom or built-in type
4. Lots of long stdlib functions were renamed to short methods
5. Fift output now contains original .tolk lines as comments
Closes #1152

Update docs for Tolk v0.12

---

cspell.json
docs/v3/documentation/infra/nodes/mytonctrl/mytonctrl-overview.mdx

Feat: enhance MyTonCtrl documentation with installation instructions and flags:
- https://docs.ton.org/v3/documentation/infra/nodes/mytonctrl/mytonctrl-overview
Closes https://github.com/ton-community/ton-docs/issues/1143 .

MyTonCtrl overview update

---

docs/v3/documentation/smart-contracts/contracts-specs/nominator-pool.mdx
docs/v3/guidelines/smart-contracts/howto/nominator-pool.mdx

Cost breakdown for the pages:
- https://docs.ton.org/v3/documentation/smart-contracts/contracts-specs/nominator-pool
- https://docs.ton.org/v3/guidelines/smart-contracts/howto/nominator-pool
Closes https://github.com/ton-community/ton-docs/issues/1157 .

Formatting and enhance cost breakdown in Nominator Pool Documention

---

cspell.json
docs/v3/documentation/smart-contracts/limits.md
sidebars/documentation.js

I've added a reference page outlining key blockchain limits developers should know. This includes important constraints like maximum transaction size, gas limits, and other critical thresholds that affect smart contract operations.
Closes issues: https://github.com/ton-community/ton-docs/issues/1149 https://github.com/ton-community/ton-docs/issues/746

Blockchain limits page

---

docs/v3/documentation/smart-contracts/getting-started/javascript.mdx
docs/v3/guidelines/dapps/overview.mdx
docs/v3/guidelines/quick-start/developing-smart-contracts/func-tolk-folder/blueprint-sdk-overview.mdx
docs/v3/guidelines/quick-start/developing-smart-contracts/func-tolk-folder/deploying-to-network.mdx
docs/v3/guidelines/quick-start/developing-smart-contracts/func-tolk-folder/processing-messages.mdx
docs/v3/guidelines/quick-start/developing-smart-contracts/func-tolk-folder/storage-and-get-methods.mdx
docs/v3/guidelines/quick-start/developing-smart-contracts/setup-environment.mdx
docs/v3/guidelines/quick-start/developing-smart-contracts/tact-folder/tact-blueprint-sdk-overview.mdx
docs/v3/guidelines/quick-start/developing-smart-contracts/tact-folder/tact-deploying-to-network.mdx
docs/v3/guidelines/quick-start/developing-smart-contracts/tact-folder/tact-storage-and-get-methods.mdx
docs/v3/guidelines/quick-start/getting-started.mdx
docs/v3/guidelines/smart-contracts/get-methods.md
docs/v3/guidelines/smart-contracts/testing/writing-test-examples.mdx

removing SDK from "Blueprint SDK"
Closes https://github.com/ton-community/ton-docs/issues/1182.

1182-fix-blueprint-sdk

---

docs/v3/documentation/data-formats/tlb/msg-tlb.mdx
docs/v3/guidelines/quick-start/blockchain-interaction/reading-from-network.mdx
docs/v3/guidelines/quick-start/blockchain-interaction/writing-to-network.mdx
docs/v3/guidelines/quick-start/developing-smart-contracts/func-tolk-folder/blueprint-sdk-overview.mdx
docs/v3/guidelines/quick-start/developing-smart-contracts/func-tolk-folder/deploying-to-network.mdx
docs/v3/guidelines/quick-start/developing-smart-contracts/func-tolk-folder/processing-messages.mdx
docs/v3/guidelines/quick-start/developing-smart-contracts/func-tolk-folder/storage-and-get-methods.mdx
docs/v3/guidelines/quick-start/developing-smart-contracts/tact-folder/tact-blueprint-sdk-overview.mdx
docs/v3/guidelines/quick-start/developing-smart-contracts/tact-folder/tact-deploying-to-network.mdx
docs/v3/guidelines/quick-start/developing-smart-contracts/tact-folder/tact-storage-and-get-methods.mdx
docs/v3/guidelines/quick-start/getting-started.mdx
sidebars/guidelines.js

Improve user flow in the Onboarding guide section.
Closes https://github.com/ton-community/ton-docs/issues/1151.

Onboarding guide: user flow new pt. 2 

---

docs/v3/guidelines/dapps/cookbook.mdx

Fix broken code in "Writing comments: long strings in snake format"

---

cspell.json
docs/v3/documentation/smart-contracts/tolk/changelog.mdx
docs/v3/documentation/smart-contracts/tolk/overview.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/create-message.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-detail.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-short.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/lazy-loading.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/mutability.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/pack-to-from-cells.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/stdlib.mdx
sidebars/documentation.js
src/theme/prism/prism-tolk.js

Tolk v1.0 is finally releasing!
* https://github.com/ton-blockchain/ton/pull/1741
Closes #1312.
1. The magic `lazy` keyword — lazy loading, partial loading, partial updating
2. Auto-detect and inline functions at the compiler level
3. Various optimizations for gas efficiency
4. `onInternalMessage` and `onBouncedMessage`, TVM 11 support
5. Custom pack/unpack serializers for custom types

Update docs for Tolk v1.0

---

docs/v3/guidelines/smart-contracts/howto/wallet.mdx

Here is 404 in How to section for Addresses section

fix: 404 in how to

---

docs/v3/concepts/dive-into-ton/go-from-ethereum/solidity-vs-func.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-concepts-dive-into-ton-go-from-ethereum-solidity-vs-func.mdx` into `main`.
- M: `docs/v3/concepts/dive-into-ton/go-from-ethereum/solidity-vs-func.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/concepts/dive-into-ton/go-from-ethereum/solidity-vs-func.mdx?plain=1#L5
Remove the trailing space so the heading reads “## Introduction”.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/concepts/dive-into-ton/go-from-ethereum/solidity-vs-func.mdx?plain=1#L8
Replace “strictly typed” with “statically typed” for accuracy and consistency.
--- …

Split: update docs/v3/concepts/dive-into-ton/go-from-ethereum/solidity-vs-func.mdx (from ai-fixes-big vs main)

---

docs/v3/concepts/dive-into-ton/go-from-ethereum/tvm-vs-evm.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-concepts-dive-into-ton-go-from-ethereum-tvm-vs-evm.mdx` into `main`.
- M: `docs/v3/concepts/dive-into-ton/go-from-ethereum/tvm-vs-evm.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/concepts/dive-into-ton/go-from-ethereum/tvm-vs-evm.mdx?plain=1#L8
Change the heading text from “Differences of TVM and EVM” to “Differences between TVM and EVM” for idiomatic English.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/concepts/dive-into-ton/go-from-ethereum/tvm-vs-evm.mdx?plain=1#L10
Replace “Data presentation” with “Data representation” to correctly describe how data is …

Split: update docs/v3/concepts/dive-into-ton/go-from-ethereum/tvm-vs-evm.mdx (from ai-fixes-big vs main)

---

docs/v3/contribute/content-standardization.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-contribute-content-standardization.mdx` into `main`.
- M: `docs/v3/contribute/content-standardization.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/contribute/content-standardization.mdx?plain=1#L50
Use a single emphasis marker across the page (prefer underscores) and avoid nesting italics with the same marker; e.g., rewrite the sentence to avoid nested italics and quote “would” instead; also align earlier italics at L34 and L87 to use underscores.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/contribute/content-standardization.mdx?plain=1#L91-L94
Change to …

Split: update docs/v3/contribute/content-standardization.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/ton-connect/guidelines/developers.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-ton-connect-guidelines-developers.mdx` into `main`.
- M: `docs/v3/guidelines/ton-connect/guidelines/developers.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/ton-connect/business/ton-connect-for-business.mdx?plain=1#L39-L40
Remove unverified future claims and mobile SDK listings; state currently supported SDKs (e.g., JavaScript and Python) and link to the canonical list (docs/v3/guidelines/ton-connect/guidelines/developers.mdx).
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/ton-connect/guidelines/developers.mdx?plain=1
Change …

Split: update docs/v3/guidelines/ton-connect/guidelines/developers.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/ton-connect/overview.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-ton-connect-overview.mdx` into `main`.
- M: `docs/v3/guidelines/ton-connect/overview.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/ton-connect/overview.mdx?plain=1#L3
The import statement for Button lacks a trailing semicolon; add it for consistency: import Button from '@site/src/components/button';.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/ton-connect/overview.mdx?plain=1#L10-L14
The video may not autoplay inline on iOS Safari; add playsInline to the <video> element (e.g., <video ... muted={true} autoPlay={true} …

Split: update docs/v3/guidelines/ton-connect/overview.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/ton-connect/cookbook/ton-transfer.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-ton-connect-cookbook-ton-transfer.mdx` into `main`.
- M: `docs/v3/guidelines/ton-connect/cookbook/ton-transfer.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/ton-connect/cookbook/ton-transfer.mdx?plain=1
Update the "user-friendly format" link to /v3/documentation/smart-contracts/addresses/address-formats#user-friendly-address because the current target points to a non-existent anchor.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/ton-connect/cookbook/ton-transfer.mdx?plain=1
Change TabItem labels from "@tonconnect/react-ui" to …

Split: update docs/v3/guidelines/ton-connect/cookbook/ton-transfer.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/quick-start/developing-smart-contracts/tact-folder/tact-storage-and-get-methods.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-quick-start-developing-smart-contracts-tact-folder-tact-storage-and-get-methods.mdx` into `main`.
- M: `docs/v3/guidelines/quick-start/developing-smart-contracts/tact-folder/tact-storage-and-get-methods.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/quick-start/developing-smart-contracts/tact-folder/tact-storage-and-get-methods.mdx?plain=1#L2-L3
Tabs and TabItem are imported but never used; remove these imports to eliminate lint warnings and reduce bundle size.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/quick-start/developing-s …

Split: update docs/v3/guidelines/quick-start/developing-smart-contracts/tact-folder/tact-storage-and-get-methods.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/quick-start/developing-smart-contracts/tact-folder/tact-deploying-to-network.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-quick-start-developing-smart-contracts-tact-folder-tact-deploying-to-network.mdx` into `main`.
- M: `docs/v3/guidelines/quick-start/developing-smart-contracts/tact-folder/tact-deploying-to-network.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/quick-start/developing-smart-contracts/tact-folder/tact-deploying-to-network.mdx?plain=1#you-already-know-the-address
Replace the word "nonexistent" with the canonical term "nonexist" when describing an empty address state.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/quick-start/developing …

Split: update docs/v3/guidelines/quick-start/developing-smart-contracts/tact-folder/tact-deploying-to-network.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/dapps/tutorials/telegram-bot-examples/accept-payments-in-a-telegram-bot.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-dapps-tutorials-telegram-bot-examples-accept-payments-in-a-telegram-bot.mdx` into `main`.
- M: `docs/v3/guidelines/dapps/tutorials/telegram-bot-examples/accept-payments-in-a-telegram-bot.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/dapps/tutorials/telegram-bot-examples/accept-payments-in-a-telegram-bot.mdx?plain=1#L9-L11
Add a link to the overview so readers can navigate: change “Telegram Mini Apps” to “[Telegram Mini Apps](/v3/guidelines/dapps/tma/overview)”.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/dapps/tutorials/telegra …

Split: update docs/v3/guidelines/dapps/tutorials/telegram-bot-examples/accept-payments-in-a-telegram-bot.mdx (from ai-fixes-big vs main)

---

docs/v3/documentation/smart-contracts/addresses/address-states.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-documentation-smart-contracts-addresses-address-states.mdx` into `main`.
- M: `docs/v3/documentation/smart-contracts/addresses/address-states.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/documentation/smart-contracts/addresses.mdx?plain=1
This file is empty; either populate it as an index with an H1 “Addresses”, a brief overview, and links to docs/v3/documentation/smart-contracts/addresses/address.mdx, docs/v3/documentation/smart-contracts/addresses/address-formats.mdx, and docs/v3/documentation/smart-contracts/addresses/address-states.mdx, or add a redirect in redirects/redirects.json from …

Split: update docs/v3/documentation/smart-contracts/addresses/address-states.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/smart-contracts/testing/blueprint-config.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-smart-contracts-testing-blueprint-config.mdx` into `main`.
- M: `docs/v3/guidelines/smart-contracts/testing/blueprint-config.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/testing/blueprint-config.mdx?plain=1#L3
Replace “pre-defines” with the closed form “predefines” for style consistency.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/testing/blueprint-config.mdx?plain=1#L21
Insert a comma: “After that, you can simply call:”.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd93 …

Split: update docs/v3/guidelines/smart-contracts/testing/blueprint-config.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/quick-start/developing-smart-contracts/func-tolk-folder/processing-messages.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-quick-start-developing-smart-contracts-func-tolk-folder-processing-messages.mdx` into `main`.
- M: `docs/v3/guidelines/quick-start/developing-smart-contracts/func-tolk-folder/processing-messages.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/quick-start/developing-smart-contracts/func-tolk-folder/processing-messages.mdx?plain=1#L8
Replace “we modified our smart contract interaction with `storage`, `get methods`, and learned the basic smart contract development flow.” with “we modified our smart contract to interact with storage and get methods, and learned the basic smart contract development …

Split: update docs/v3/guidelines/quick-start/developing-smart-contracts/func-tolk-folder/processing-messages.mdx (from ai-fixes-big vs main)

---

docs/v3/documentation/dapps/defi/ton-payments.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-documentation-dapps-defi-ton-payments.mdx` into `main`.
- M: `docs/v3/documentation/dapps/defi/ton-payments.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/documentation/dapps/defi/ton-payments.mdx?plain=1#L7-L8
Replace “wait five seconds until the block … is confirmed.” with “wait for block confirmation.”
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/documentation/dapps/defi/ton-payments.mdx?plain=1#L24
Change “You can use prepared SDKs:” to “You can use the following SDKs:”.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da369 …

Split: update docs/v3/documentation/dapps/defi/ton-payments.mdx (from ai-fixes-big vs main)

---

docs/v3/documentation/smart-contracts/fift/fift-deep-dive.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-documentation-smart-contracts-fift-fift-deep-dive.mdx` into `main`.
- M: `docs/v3/documentation/smart-contracts/fift/fift-deep-dive.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/documentation/smart-contracts/fift/fift-deep-dive.mdx?plain=1#fift-deep-dive
Change “bag-of-cells (BoC)” to “bag of cells (BoC)” on first mention and use “BoC” thereafter.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/documentation/smart-contracts/fift/fift-deep-dive.mdx?plain=1#L20-L23
Prefix the code fence with ```fift to enable proper syntax highlighting.
--- …
```

Split: update docs/v3/documentation/smart-contracts/fift/fift-deep-dive.mdx (from ai-fixes-big vs main)

---

docs/v3/documentation/tvm/specification/runvm.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-documentation-tvm-specification-runvm.mdx` into `main`.
- M: `docs/v3/documentation/tvm/specification/runvm.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/documentation/tvm/specification/runvm.mdx?plain=1#L8
Merge the two consecutive "This ..." sentences into one for flow (e.g., a single sentence that both describes safe data retrieval and that the caller’s state remains unaffected).
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/documentation/tvm/specification/runvm.mdx?plain=1#L12-L13
Replace exitcode with exit_code in the table’s stack signatures to match the …

Split: update docs/v3/documentation/tvm/specification/runvm.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/ton-connect/cookbook/cells.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-ton-connect-cookbook-cells.mdx` into `main`.
- M: `docs/v3/guidelines/ton-connect/cookbook/cells.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/ton-connect/cookbook/cells.mdx?plain=1#L19-L32
Replace “TON Blockchain” with “TON blockchain” to match site-wide style.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/ton-connect/cookbook/cells.mdx?plain=1#L25-L32, #L40-L49, #L157-L166
Replace imports from "@ton/ton" with "@ton/core" and rename the second TabItem label/value from "@ton/ton" to "@ton/core" so the opening library list and …

Split: update docs/v3/guidelines/ton-connect/cookbook/cells.mdx (from ai-fixes-big vs main)

---

docs/v3/documentation/smart-contracts/func/docs/comments.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-documentation-smart-contracts-func-docs-comments.mdx` into `main`.
- M: `docs/v3/documentation/smart-contracts/func/docs/comments.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/documentation/smart-contracts/func/docs/comments.mdx?plain=1#L13-L15
Replace “Unlike other languages, FunC allows nested multi-line comments.” with the neutral statement “FunC allows nested multi-line comments.”
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/documentation/smart-contracts/func/docs/comments.mdx?plain=1#L24
Rewrite the sentence to: “Within a multi-line comment, `;;` starts a …

Split: update docs/v3/documentation/smart-contracts/func/docs/comments.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/dapps/transactions/foundations-of-blockchain.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-dapps-transactions-foundations-of-blockchain.mdx` into `main`.
- M: `docs/v3/guidelines/dapps/transactions/foundations-of-blockchain.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/dapps/transactions/foundations-of-blockchain.mdx?plain=1#L18-L22
Change to: “An actor is an independent entity with its own state and behavior.”
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/dapps/transactions/foundations-of-blockchain.mdx?plain=1#L24,L55,L61,L75,L90,L195,L265,L276,L293,L307
Replace empty alt text with concise, descriptive alt text for …

Split: update docs/v3/guidelines/dapps/transactions/foundations-of-blockchain.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/dapps/tutorials/mint-your-first-token.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-dapps-tutorials-mint-your-first-token.mdx` into `main`.
- M: `docs/v3/guidelines/dapps/tutorials/mint-your-first-token.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/dapps/tutorials/mint-your-first-token.mdx?plain=1
Capitalize Jetton in the page title and section headings for consistency with cross-doc references; e.g., change "Mint your first jetton" → "Mint your first Jetton" and "Deploy a jetton" → "Deploy a Jetton" (see docs/v3/documentation/dapps/defi/tokens.mdx#tutorials and docs/v3/guidelines/dapps/asset-processing/jettons.mdx#jetton-processing).
--- …

Split: update docs/v3/guidelines/dapps/tutorials/mint-your-first-token.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/smart-contracts/testing/collect-contract-gas-metric.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-smart-contracts-testing-collect-contract-gas-metric.mdx` into `main`.
- M: `docs/v3/guidelines/smart-contracts/testing/collect-contract-gas-metric.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/testing/collect-contract-gas-metric.mdx?plain=1#L13-L18
The closing ::: of the first tip block is indented by two spaces; unindent it so the fence is exactly ::: aligned with the opening :::tip.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/testing/collect-contract-gas-metric.mdx?plain=1#L26-L35
Replace “and …

Split: update docs/v3/guidelines/smart-contracts/testing/collect-contract-gas-metric.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/ton-connect/cookbook/nft-transfer.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-ton-connect-cookbook-nft-transfer.mdx` into `main`.
- M: `docs/v3/guidelines/ton-connect/cookbook/nft-transfer.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/ton-connect/cookbook/nft-transfer.mdx?plain=1#L22
Change “The `body` message typically should be done according the following way:” to “The `body` message should be constructed as follows:”.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/ton-connect/cookbook/nft-transfer.mdx?plain=1#L25-L38,L41
Add `Address` to the import (`import { beginCell, Address, toNano } from …

Split: update docs/v3/guidelines/ton-connect/cookbook/nft-transfer.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/dapps/cookbook.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-dapps-cookbook.mdx` into `main`.
- M: `docs/v3/guidelines/dapps/cookbook.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/documentation/smart-contracts/addresses/address-formats.mdx?plain=1#address-conversion
Replace the root ton-core repo link with internal cross-references to docs/v3/guidelines/dapps/cookbook.mdx#how-to-convert-between-user-friendly-and-raw-addresses-assemble-and-extract-them-from-strings and docs/v3/guidelines/dapps/apis-sdks/sdk.mdx; if keeping an external reference, update it to the stable file URL https://github.com/ton-org/ton-core/blob/main/src/address/Address.spec.ts.
--- …

Split: update docs/v3/guidelines/dapps/cookbook.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/smart-contracts/security/things-to-focus.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-smart-contracts-security-things-to-focus.mdx` into `main`.
- M: `docs/v3/guidelines/smart-contracts/security/things-to-focus.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/security/things-to-focus.mdx?plain=1#L11-L12
Identifiers must not include ; , ( ) [ ] spaces/tabs, ~, or . (only function names may start with ~ or .), so remove the “including commas” claim, fix examples (e.g., drop `~bits` as a variable and show it only as a function name example), and improve wording to “valid”, “e.g.,” and “variable and function names”.
--- …

Split: update docs/v3/guidelines/smart-contracts/security/things-to-focus.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/smart-contracts/security/secure-programming.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-smart-contracts-security-secure-programming.mdx` into `main`.
- M: `docs/v3/guidelines/smart-contracts/security/secure-programming.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/security/secure-programming.mdx?plain=1#L3
ThemedImage is imported but never used; delete the import to avoid dead code.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/security/secure-programming.mdx?plain=1#L11
Replace “Liquidity Pairs in an Automated Market Maker” with “liquidity pairs in an automated market maker (AMM)” …

Split: update docs/v3/guidelines/smart-contracts/security/secure-programming.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/smart-contracts/howto/multisig-js.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-smart-contracts-howto-multisig-js.mdx` into `main`.
- M: `docs/v3/guidelines/smart-contracts/howto/multisig-js.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/howto/multisig-js.mdx?plain=1#L2
Change to: "At the end of this guide, you will deploy a multisig wallet and send transactions using the TON TypeScript libraries."
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/howto/multisig-js.mdx?plain=1#L8-L12
Replace maintainer-focused, tool-specific text with a reader-facing, tool-agnostic note, e.g., …

Split: update docs/v3/guidelines/smart-contracts/howto/multisig-js.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/smart-contracts/howto/airdrop-claim-best-practice.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-smart-contracts-howto-airdrop-claim-best-practice.mdx` into `main`.
- M: `docs/v3/guidelines/smart-contracts/howto/airdrop-claim-best-practice.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/howto/airdrop-claim-best-practice.mdx?plain=1
Standardize all occurrences to “double‑spend” (including headings and inline identifiers), replacing “double spend” and “double_spend” when referring to the contract.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/howto/airdrop-claim-best-practice.mdx?plain=1
Rewrite …

Split: update docs/v3/guidelines/smart-contracts/howto/airdrop-claim-best-practice.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/smart-contracts/howto/single-nominator-pool.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-smart-contracts-howto-single-nominator-pool.mdx` into `main`.
- M: `docs/v3/guidelines/smart-contracts/howto/single-nominator-pool.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/howto/single-nominator-pool.mdx?plain=1#L12
Change "### Set up single nominator mode" to "## Set up single nominator mode" to align with peer second-level sections.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/howto/single-nominator-pool.mdx?plain=1#L12
Update the heading to "Set up single-nominator mode" for consistent …

Split: update docs/v3/guidelines/smart-contracts/howto/single-nominator-pool.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/dapps/asset-processing/compressed-nfts.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-dapps-asset-processing-compressed-nfts.mdx` into `main`.
- M: `docs/v3/guidelines/dapps/asset-processing/compressed-nfts.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/dapps/asset-processing/compressed-nfts.mdx?plain=1#L17
Change the heading to “Supporting compressed NFTs in wallets and marketplaces” for grammatical correctness and consistency.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/dapps/asset-processing/compressed-nfts.mdx?plain=1#L101-L108
After the git clone command, add “cd cnft-toolbox” so subsequent docker-compose …

Split: update docs/v3/guidelines/dapps/asset-processing/compressed-nfts.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/dapps/asset-processing/nft-processing/metadata-parsing.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-dapps-asset-processing-nft-processing-metadata-parsing.mdx` into `main`.
- M: `docs/v3/guidelines/dapps/asset-processing/nft-processing/metadata-parsing.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/dapps/asset-processing/nft-processing/metadata-parsing.mdx?plain=1#L5
“The metadata standard covering NFTs, NFT collections, and jettons, is outlined …” → remove the comma after “jettons”.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/dapps/asset-processing/nft-processing/metadata-parsing.mdx?plain=1#L15,L77
Soften “must be prefixed …

Split: update docs/v3/guidelines/dapps/asset-processing/nft-processing/metadata-parsing.mdx (from ai-fixes-big vs main)

---

docs/v3/documentation/smart-contracts/message-management/external-messages.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-documentation-smart-contracts-message-management-external-messages.mdx` into `main`.
- M: `docs/v3/documentation/smart-contracts/message-management/external-messages.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/documentation/smart-contracts/message-management/external-messages.mdx?plain=1
Remove inline code formatting around the plain-text phrases "sent from the outside" (line 5) and "malicious actor could extract" (line 15); they are not code and should be regular text (or italics).
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/documentation/smart-contracts/me …

Split: update docs/v3/documentation/smart-contracts/message-management/external-messages.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/nodes/persistent-states.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-nodes-persistent-states.mdx` into `main`.
- M: `docs/v3/guidelines/nodes/persistent-states.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/nodes/persistent-states.mdx?plain=1
Change “every 1.5 days” to “every 2^17 seconds (~1.52 days)” to reflect an approximate day value.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/nodes/persistent-states.mdx?plain=1
Change “2^18 seconds (3 days)” and “2^19 seconds (6 days)” to “2^18 seconds (~3 days)” and “2^19 seconds (~6 days)”.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f7 …

Split: update docs/v3/guidelines/nodes/persistent-states.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/smart-contracts/howto/compile/compilation-instructions.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-smart-contracts-howto-compile-compilation-instructions.mdx` into `main`.
- M: `docs/v3/guidelines/smart-contracts/howto/compile/compilation-instructions.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/howto/compile/compilation-instructions.mdx?plain=1
Replace all instances of "MacOS" with "macOS" in headings and prose.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/howto/compile/compilation-instructions.mdx?plain=1#common
Change “Then run the following in a terminal of Linux or MacOS:” to “Then run …

Split: update docs/v3/guidelines/smart-contracts/howto/compile/compilation-instructions.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/nodes/running-nodes/secure-guidelines.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-nodes-running-nodes-secure-guidelines.mdx` into `main`.
- M: `docs/v3/guidelines/nodes/running-nodes/secure-guidelines.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/nodes/running-nodes/secure-guidelines.mdx?plain=1
Change the H1 from "Secure guidelines for nodes" to "Security Guidelines for Nodes" for clarity and Title Case consistency.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/nodes/running-nodes/secure-guidelines.mdx?plain=1
Replace "Below are a set of guidelines to enhance node security:" with either "Below is a set of …

Split: update docs/v3/guidelines/nodes/running-nodes/secure-guidelines.mdx (from ai-fixes-big vs main)

---

docs/v3/documentation/smart-contracts/func/docs/global_variables.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-documentation-smart-contracts-func-docs-global_variables.mdx` into `main`.
- M: `docs/v3/documentation/smart-contracts/func/docs/global_variables.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/documentation/smart-contracts/func/docs/global_variables.mdx?plain=1#L5-L6
Replace “function declarations/definitions” and “the latter” with explicit parallel wording: “A FunC program is a list of function declarations, function definitions, and global variable declarations. This section focuses on global variables.”
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/documentati …

Split: update docs/v3/documentation/smart-contracts/func/docs/global_variables.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/smart-contracts/fee-calculation.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-smart-contracts-fee-calculation.mdx` into `main`.
- M: `docs/v3/guidelines/smart-contracts/fee-calculation.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/fee-calculation.mdx?plain=1#L3
Change the H1 to "Fee calculation" (singular) instead of "Fees calculation".
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/smart-contracts/fee-calculation.mdx?plain=1#L7
Update the link to /v3/documentation/smart-contracts/transaction-fees/fees#elements-of-the-transaction-fee so it matches the target heading.
--- …

Split: update docs/v3/guidelines/smart-contracts/fee-calculation.mdx (from ai-fixes-big vs main)

---

docs/v3/guidelines/nodes/maintenance-guidelines/mytonctrl-remote-controller.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-guidelines-nodes-maintenance-guidelines-mytonctrl-remote-controller.mdx` into `main`.
- M: `docs/v3/guidelines/nodes/maintenance-guidelines/mytonctrl-remote-controller.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/nodes/maintenance-guidelines/mytonctrl-remote-controller.mdx?plain=1
Replace "There are some advantages of using that:" with "There are several advantages to this setup:" for natural wording.
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/guidelines/nodes/maintenance-guidelines/mytonctrl-remote-controller.mdx?plain=1
Use "TON node" for the …

Split: update docs/v3/guidelines/nodes/maintenance-guidelines/mytonctrl-remote-controller.mdx (from ai-fixes-big vs main)

---

docs/v3/documentation/smart-contracts/func/changelog.mdx

This PR was generated from branch `split/ai-fixes-big-docs-v3-documentation-smart-contracts-func-changelog.mdx` into `main`.
- M: `docs/v3/documentation/smart-contracts/func/changelog.mdx`
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/documentation/smart-contracts/func/changelog.mdx?plain=1#L3
The H1 title has a trailing space; remove it so the line reads exactly "# History of FunC".
---
https://github.com/ton-community/ton-docs/blob/ee42357f5954f777d7ebd937b2683096da3699bf/docs/v3/documentation/smart-contracts/func/changelog.mdx?plain=1#L12-L16, L48-L50
Add terminal periods to these bullet items to match the punctuation style used elsewhere in the list.
--- …

Split: update docs/v3/documentation/smart-contracts/func/changelog.mdx (from ai-fixes-big vs main)

---

docs/v3/documentation/smart-contracts/tolk/changelog.mdx
docs/v3/documentation/smart-contracts/tolk/language-guide.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-detail.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/in-short.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/mutability.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/pack-to-from-cells.mdx
docs/v3/documentation/smart-contracts/tolk/tolk-vs-func/stdlib.mdx
src/css/custom.css
src/theme/prism/prism-tolk.js

Update documentation for Tolk Language according to changes in Tolk v1.1.
* https://github.com/ton-blockchain/ton/pull/1795
1 `map<K, V>` — a convenient zero-overhead wrapper over TVM dictionaries
2. `enum` — group numeric constants into a distinct type
3. `private` and `readonly` fields in structures
4. Enhanced overload resolution and partial specialization
Closes #1754

Update docs for Tolk v1.1
